# coding: utf-8

"""
    ai/h2o/mlops/deployer/v1/artifact_composition.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from _h2o_mlops_client.deployer.configuration import Configuration


class DeployEndpoint(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'method': 'DeployHttpMethod'
    }

    attribute_map = {
        'url': 'url',
        'method': 'method'
    }

    def __init__(self, url=None, method=None, local_vars_configuration=None):  # noqa: E501
        """DeployEndpoint - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._url = None
        self._method = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if method is not None:
            self.method = method

    @property
    def url(self):
        """Gets the url of this DeployEndpoint.  # noqa: E501

        POST endpoint URL of the deployment, typically in the form <ip/host>:<port>/<path>. This is the empty string when the endpoint is not available.  # noqa: E501

        :return: The url of this DeployEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this DeployEndpoint.

        POST endpoint URL of the deployment, typically in the form <ip/host>:<port>/<path>. This is the empty string when the endpoint is not available.  # noqa: E501

        :param url: The url of this DeployEndpoint.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def method(self):
        """Gets the method of this DeployEndpoint.  # noqa: E501


        :return: The method of this DeployEndpoint.  # noqa: E501
        :rtype: DeployHttpMethod
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this DeployEndpoint.


        :param method: The method of this DeployEndpoint.  # noqa: E501
        :type method: DeployHttpMethod
        """

        self._method = method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeployEndpoint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DeployEndpoint):
            return True

        return self.to_dict() != other.to_dict()
