class StrategyIDIterator:
    def __new__(cls): ...
    @classmethod
    def initialize(cls, strategy_ids) -> None: ...
    @classmethod
    def get_active_strategy_id(cls): ...
    @classmethod
    def set_active_strategy_id(cls, strategy_key) -> None: ...
    @classmethod
    def update_to_next_strategy(cls): ...
