# (POLITE) MASU FORM ENDINGS
MASU_POSITIVE_NONPAST = "ます"
MASU_NEGATIVE_NONPAST = "ません"
MASU_POSITIVE_PAST = "ました"
MASU_NEGATIVE_PAST = "ませんでした"

# (PLAIN) KATTA FORM ENDING
NAKATTA_ENDING = "なかった"

# (PLAIN) NAI ENDING
NAI_ENDING = "ない"

# TE FORM ENDING
TE_FORM_PLAIN_NEGATIVE_ENDING = "なくて"
TE_FORM_POLITE_POSITIVE_ENDING = "まして"
TE_FORM_POLITE_NEGATIVE_ENDING = "ませんでして"

# VOLITIONAL FORM ENDINGS
VOLITIONAL_POLITE_ENDING = "ましょう"
VOLITIONAL_POLITE_COPULA = "でしょう"
VOLITIONAL_PLAIN_COPULA = "だろう"
VOLITIONAL_ICHIDAN_PLAIN_ENDING = "よう"

# POTENTIAL FORM
POTENTIAL_POLITE_ICHIDAN_ENDING = "られます"
POTENTIAL_PLAIN_ICHIDAN_ENDING = "られる"

# PASSIVE FORM ENDINGS
PASSIVE_ICHIDAN_PLAIN_POSITIVE_ENDING = "られる"
PASSIVE_ICHIDAN_PLAIN_NEGATIVE_ENDING = "られない"
PASSIVE_ICHIDAN_POLITE_POSITIVE_ENDING = "られます"
PASSIVE_ICHIDAN_POLITE_NEGATIVE_ENDING = "られません"

# PROVISIONAL VERB ENDINGS
PROVISIONAL_ICHIDAN_PLAIN_NEGATIVE_ENDING = "なければ"

# TARI FORM
TARI_ENDING = "たり"
DARI_ENDING = "だり"
TARI_FORM_PLAIN_NEGATIVE_ENDING = "なかったり"
TARI_FORM_POLITE_POSITIVE_ENDING = "ましたり"
TARI_FORM_POLITE_NEGATIVE_ENDING = "ませんでしたり"

# DA COPULA ENDINGS
PLAIN_DA_POSITIVE_ENDING = "だ"
POLITE_DA_POSITIVE_ENDING = "です"
CONDITIONAL_DA_PLAIN_POSITIVE_ENDING = "なら"
PRESUMPTIVE_DA_PLAIN_POSITIVE_ENDING = "だろう"
PRESUMPTIVE_DA_POLITE_POSITIVE_ENDING = "でしょう"
TE_FORM_DA_PLAIN_POSITIVE_ENDING = "で"
TE_FORM_DA_POLITE_POSITIVE_ENDING = "でして"
PAST_DA_PLAIN_POSITIVE_ENDING = "だった"
PAST_DA_POLITE_POSITIVE_ENDING = "でした"
TARA_DA_PLAIN_POSITIVE_ENDING = "だったら"
TARA_DA_POLITE_POSITIVE_ENDING = "でしたら"
PLAIN_DA_NEGATIVE_ENDING = "ではない"
POLITE_DA_NEGATIVE_ENDING = "ではありません"
PAST_DA_PLAIN_NEGATIVE_ENDING = "なかった"
