from _typeshed import Incomplete
from src.almanak_library.enums import Chain as Chain, Network as Network
from src.utils.utils import get_blocknative_tip as get_blocknative_tip, get_logger as get_logger, get_web3_by_network_and_chain as get_web3_by_network_and_chain, retry_get_block as retry_get_block

logger: Incomplete

def get_gas_buffer(chain: Chain, network: Network) -> float: ...
def get_approval_buffer(chain: Chain, network: Network) -> float: ...
def get_fee_buffer(chain: Chain, network: Network) -> float: ...
def get_transaction_fees(chain: Chain, network: Network, block_identifier: Incomplete | None = None) -> dict[str, int]: ...
