
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-01T06:12:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad45449ff160a8a42024f58e4e0fc873798b0919",
 "version": "4.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
