from typing import Optional, List

__all__: List[str]

class Rng:
    def __init__(self, seed: Optional[int] = None): ...
    def random_bool(self, ratio: float = 0.5) -> bool: ...
    def random_ratio(self, numerator: int, denominator: int) -> bool: ...
    def random_int(self, lower: int, upper: int) -> int: ...
    def random_float(self) -> float: ...
