# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GroupByEnum(object):

    """Implementation of the 'GroupBy' enum.

    Data can be grouped by `daily` or `hourly`. Metrics with histogram
    response (`completion_percent`, `completion_percent_by_views`) can not be
    grouped hourly

    Attributes:
        DAILY: The enum member of type str.
        HOURLY: The enum member of type str.

    """
    DAILY = 'daily'

    HOURLY = 'hourly'

