# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from gumletrestapis.api_helper import APIHelper


class Output4(object):

    """Implementation of the 'Output4' model.

    Attributes:
        playback_url (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "playback_url": 'playback_url'
    }

    _optionals = [
        'playback_url',
    ]

    def __init__(self,
                 playback_url=APIHelper.SKIP):
        """Constructor for the Output4 class"""

        # Initialize members of the class
        if playback_url is not APIHelper.SKIP:
            self.playback_url = playback_url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        playback_url = dictionary.get("playback_url") if dictionary.get("playback_url") else APIHelper.SKIP
        # Return an object of this model
        return cls(playback_url)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'playback_url={(self.playback_url if hasattr(self, "playback_url") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'playback_url={(self.playback_url if hasattr(self, "playback_url") else None)!s})')
