# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortByEnum(object):

    """Implementation of the 'sortBy' enum.

    Attributes:
        TITLE: The enum member of type str.
        DURATION: The enum member of type str.
        UPLOADED_AT: The enum member of type str.
        CREATED_AT: The enum member of type str.

    """
    TITLE = 'title'

    DURATION = 'duration'

    UPLOADED_AT = 'uploaded_at'

    CREATED_AT = 'created_at'

