# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 532)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabOption = QtWidgets.QTabWidget(self.centralWidget)
        self.tabOption.setGeometry(QtCore.QRect(0, 0, 281, 531))
        self.tabOption.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabOption.setObjectName("tabOption")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.groupBoxDevices = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBoxDevices.setGeometry(QtCore.QRect(6, 0, 261, 161))
        self.groupBoxDevices.setObjectName("groupBoxDevices")
        self.listViewDevices = QtWidgets.QListView(self.groupBoxDevices)
        self.listViewDevices.setGeometry(QtCore.QRect(10, 20, 241, 71))
        self.listViewDevices.setObjectName("listViewDevices")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBoxDevices)
        self.pushButtonConnect.setGeometry(QtCore.QRect(30, 110, 91, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.groupBoxDevices)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setGeometry(QtCore.QRect(140, 110, 91, 23))
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.groupBoxImages = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBoxImages.setGeometry(QtCore.QRect(6, 170, 261, 161))
        self.groupBoxImages.setObjectName("groupBoxImages")
        self.listWidgetLights = QtWidgets.QListWidget(self.groupBoxImages)
        self.listWidgetLights.setGeometry(QtCore.QRect(10, 20, 241, 101))
        self.listWidgetLights.setObjectName("listWidgetLights")
        self.checkBoxDocView = QtWidgets.QCheckBox(self.groupBoxImages)
        self.checkBoxDocView.setGeometry(QtCore.QRect(20, 130, 161, 17))
        self.checkBoxDocView.setObjectName("checkBoxDocView")
        self.groupBoxOcr = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBoxOcr.setGeometry(QtCore.QRect(6, 340, 261, 101))
        self.groupBoxOcr.setObjectName("groupBoxOcr")
        self.listWidgetOCR = QtWidgets.QListWidget(self.groupBoxOcr)
        self.listWidgetOCR.setGeometry(QtCore.QRect(10, 20, 241, 61))
        self.listWidgetOCR.setObjectName("listWidgetOCR")
        self.pushButtonStart = QtWidgets.QPushButton(self.tabOptions)
        self.pushButtonStart.setEnabled(False)
        self.pushButtonStart.setGeometry(QtCore.QRect(60, 460, 151, 31))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.tabOption.addTab(self.tabOptions, "")
        self.tabWidgetRight = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidgetRight.setGeometry(QtCore.QRect(290, 0, 731, 531))
        self.tabWidgetRight.setObjectName("tabWidgetRight")
        self.tabOCR = QtWidgets.QWidget()
        self.tabOCR.setObjectName("tabOCR")
        self.groupBoxFieldImage = QtWidgets.QGroupBox(self.tabOCR)
        self.groupBoxFieldImage.setGeometry(QtCore.QRect(10, 435, 708, 64))
        self.groupBoxFieldImage.setObjectName("groupBoxFieldImage")
        self.labelFieldImagePicture = QtWidgets.QLabel(self.groupBoxFieldImage)
        self.labelFieldImagePicture.setGeometry(QtCore.QRect(70, 14, 631, 41))
        self.labelFieldImagePicture.setText("")
        self.labelFieldImagePicture.setScaledContents(False)
        self.labelFieldImagePicture.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFieldImagePicture.setObjectName("labelFieldImagePicture")
        self.tableViewGrid = QtWidgets.QTableView(self.tabOCR)
        self.tableViewGrid.setGeometry(QtCore.QRect(0, 0, 724, 331))
        self.tableViewGrid.setSortingEnabled(True)
        self.tableViewGrid.setObjectName("tableViewGrid")
        self.groupBoxValues = QtWidgets.QGroupBox(self.tabOCR)
        self.groupBoxValues.setGeometry(QtCore.QRect(10, 340, 708, 88))
        self.groupBoxValues.setObjectName("groupBoxValues")
        self.labelRaw = QtWidgets.QLabel(self.groupBoxValues)
        self.labelRaw.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.labelRaw.setObjectName("labelRaw")
        self.labelFormatted = QtWidgets.QLabel(self.groupBoxValues)
        self.labelFormatted.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.labelFormatted.setObjectName("labelFormatted")
        self.labelStandardized = QtWidgets.QLabel(self.groupBoxValues)
        self.labelStandardized.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.labelStandardized.setObjectName("labelStandardized")
        self.labelRAWValue = QtWidgets.QLabel(self.groupBoxValues)
        self.labelRAWValue.setGeometry(QtCore.QRect(90, 16, 611, 20))
        self.labelRAWValue.setText("")
        self.labelRAWValue.setObjectName("labelRAWValue")
        self.labelFormattedValue = QtWidgets.QLabel(self.groupBoxValues)
        self.labelFormattedValue.setGeometry(QtCore.QRect(90, 38, 611, 20))
        self.labelFormattedValue.setText("")
        self.labelFormattedValue.setObjectName("labelFormattedValue")
        self.labelStandardizedValue = QtWidgets.QLabel(self.groupBoxValues)
        self.labelStandardizedValue.setGeometry(QtCore.QRect(90, 58, 611, 20))
        self.labelStandardizedValue.setText("")
        self.labelStandardizedValue.setObjectName("labelStandardizedValue")
        self.labelRAWValue.raise_()
        self.labelRaw.raise_()
        self.labelFormatted.raise_()
        self.labelStandardized.raise_()
        self.labelFormattedValue.raise_()
        self.labelStandardizedValue.raise_()
        self.tabWidgetRight.addTab(self.tabOCR, "")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.groupBoxPersonalData = QtWidgets.QGroupBox(self.tabData)
        self.groupBoxPersonalData.setGeometry(QtCore.QRect(10, 0, 571, 161))
        self.groupBoxPersonalData.setObjectName("groupBoxPersonalData")
        self.labelTabName = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabName.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.labelTabName.setObjectName("labelTabName")
        self.labelTabBirth = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabBirth.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.labelTabBirth.setObjectName("labelTabBirth")
        self.labelTabNationality = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabNationality.setGeometry(QtCore.QRect(10, 105, 61, 13))
        self.labelTabNationality.setObjectName("labelTabNationality")
        self.labelTabSex = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabSex.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.labelTabSex.setObjectName("labelTabSex")
        self.labelTabNameValue = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabNameValue.setGeometry(QtCore.QRect(80, 30, 485, 13))
        self.labelTabNameValue.setText("")
        self.labelTabNameValue.setObjectName("labelTabNameValue")
        self.labelTabBirthValue = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabBirthValue.setGeometry(QtCore.QRect(80, 80, 485, 13))
        self.labelTabBirthValue.setText("")
        self.labelTabBirthValue.setObjectName("labelTabBirthValue")
        self.labelTabNationalityValue = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabNationalityValue.setGeometry(QtCore.QRect(80, 105, 485, 13))
        self.labelTabNationalityValue.setText("")
        self.labelTabNationalityValue.setObjectName("labelTabNationalityValue")
        self.labelTabSexValue = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabSexValue.setGeometry(QtCore.QRect(80, 130, 485, 13))
        self.labelTabSexValue.setText("")
        self.labelTabSexValue.setObjectName("labelTabSexValue")
        self.labelTabNameValue2 = QtWidgets.QLabel(self.groupBoxPersonalData)
        self.labelTabNameValue2.setGeometry(QtCore.QRect(80, 56, 485, 13))
        self.labelTabNameValue2.setText("")
        self.labelTabNameValue2.setObjectName("labelTabNameValue2")
        self.groupBoxDocumentData = QtWidgets.QGroupBox(self.tabData)
        self.groupBoxDocumentData.setGeometry(QtCore.QRect(10, 170, 571, 161))
        self.groupBoxDocumentData.setObjectName("groupBoxDocumentData")
        self.labelTabIssuer = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabIssuer.setGeometry(QtCore.QRect(10, 20, 41, 13))
        self.labelTabIssuer.setObjectName("labelTabIssuer")
        self.labelTabType = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabType.setGeometry(QtCore.QRect(10, 45, 31, 13))
        self.labelTabType.setObjectName("labelTabType")
        self.labelTabPage = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabPage.setGeometry(QtCore.QRect(10, 70, 31, 13))
        self.labelTabPage.setObjectName("labelTabPage")
        self.labelTabNumber = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabNumber.setGeometry(QtCore.QRect(10, 95, 46, 13))
        self.labelTabNumber.setObjectName("labelTabNumber")
        self.labelTabValid = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabValid.setGeometry(QtCore.QRect(10, 120, 31, 13))
        self.labelTabValid.setObjectName("labelTabValid")
        self.labelTabIssuerValue = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabIssuerValue.setGeometry(QtCore.QRect(80, 20, 485, 13))
        self.labelTabIssuerValue.setText("")
        self.labelTabIssuerValue.setObjectName("labelTabIssuerValue")
        self.labelTabTypeValue = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabTypeValue.setGeometry(QtCore.QRect(80, 45, 485, 13))
        self.labelTabTypeValue.setText("")
        self.labelTabTypeValue.setObjectName("labelTabTypeValue")
        self.labelTabPageValue = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabPageValue.setGeometry(QtCore.QRect(80, 70, 485, 13))
        self.labelTabPageValue.setText("")
        self.labelTabPageValue.setObjectName("labelTabPageValue")
        self.labelTabNumberValue = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabNumberValue.setGeometry(QtCore.QRect(80, 95, 485, 13))
        self.labelTabNumberValue.setText("")
        self.labelTabNumberValue.setObjectName("labelTabNumberValue")
        self.labelTabValidValue = QtWidgets.QLabel(self.groupBoxDocumentData)
        self.labelTabValidValue.setGeometry(QtCore.QRect(80, 120, 485, 13))
        self.labelTabValidValue.setText("")
        self.labelTabValidValue.setObjectName("labelTabValidValue")
        self.groupBoxSignature = QtWidgets.QGroupBox(self.tabData)
        self.groupBoxSignature.setGeometry(QtCore.QRect(10, 340, 571, 161))
        self.groupBoxSignature.setObjectName("groupBoxSignature")
        self.labelTabSignaturePic = QtWidgets.QLabel(self.groupBoxSignature)
        self.labelTabSignaturePic.setGeometry(QtCore.QRect(20, 20, 541, 131))
        self.labelTabSignaturePic.setText("")
        self.labelTabSignaturePic.setScaledContents(False)
        self.labelTabSignaturePic.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTabSignaturePic.setObjectName("labelTabSignaturePic")
        self.groupBoxFacePhoto = QtWidgets.QGroupBox(self.tabData)
        self.groupBoxFacePhoto.setGeometry(QtCore.QRect(594, 0, 126, 161))
        self.groupBoxFacePhoto.setObjectName("groupBoxFacePhoto")
        self.labelTabFacePhotoPic = QtWidgets.QLabel(self.groupBoxFacePhoto)
        self.labelTabFacePhotoPic.setGeometry(QtCore.QRect(10, 20, 111, 131))
        self.labelTabFacePhotoPic.setText("")
        self.labelTabFacePhotoPic.setScaledContents(False)
        self.labelTabFacePhotoPic.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTabFacePhotoPic.setObjectName("labelTabFacePhotoPic")
        self.tabWidgetRight.addTab(self.tabData, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabOption.setCurrentIndex(0)
        self.tabWidgetRight.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanner Sample"))
        self.groupBoxDevices.setTitle(_translate("MainWindow", "Devices"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBoxImages.setTitle(_translate("MainWindow", "Images"))
        self.checkBoxDocView.setText(_translate("MainWindow", "Crop and rotate document"))
        self.groupBoxOcr.setTitle(_translate("MainWindow", "OCR"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.tabOption.setTabText(self.tabOption.indexOf(self.tabOptions), _translate("MainWindow", "Options"))
        self.groupBoxFieldImage.setTitle(_translate("MainWindow", "Field image"))
        self.groupBoxValues.setTitle(_translate("MainWindow", "Values"))
        self.labelRaw.setText(_translate("MainWindow", "RAW:"))
        self.labelFormatted.setText(_translate("MainWindow", "Formatted:"))
        self.labelStandardized.setText(_translate("MainWindow", "Standardized:"))
        self.tabWidgetRight.setTabText(self.tabWidgetRight.indexOf(self.tabOCR), _translate("MainWindow", "OCR"))
        self.groupBoxPersonalData.setTitle(_translate("MainWindow", "Personal Data"))
        self.labelTabName.setText(_translate("MainWindow", "Name:"))
        self.labelTabBirth.setText(_translate("MainWindow", "Birth:"))
        self.labelTabNationality.setText(_translate("MainWindow", "Nationality:"))
        self.labelTabSex.setText(_translate("MainWindow", "Sex:"))
        self.groupBoxDocumentData.setTitle(_translate("MainWindow", "Document Data"))
        self.labelTabIssuer.setText(_translate("MainWindow", "Issuer:"))
        self.labelTabType.setText(_translate("MainWindow", "Type:"))
        self.labelTabPage.setText(_translate("MainWindow", "Page:"))
        self.labelTabNumber.setText(_translate("MainWindow", "Number:"))
        self.labelTabValid.setText(_translate("MainWindow", "Valid:"))
        self.groupBoxSignature.setTitle(_translate("MainWindow", "Signature"))
        self.groupBoxFacePhoto.setTitle(_translate("MainWindow", "Face Photo"))
        self.tabWidgetRight.setTabText(self.tabWidgetRight.indexOf(self.tabData), _translate("MainWindow", "Data"))

