# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setMaximumSize(QtCore.QSize(800, 550))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBoxDevices = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxDevices.setGeometry(QtCore.QRect(10, 11, 269, 139))
        self.groupBoxDevices.setObjectName("groupBoxDevices")
        self.listViewDevices = QtWidgets.QListView(self.groupBoxDevices)
        self.listViewDevices.setGeometry(QtCore.QRect(8, 20, 251, 67))
        self.listViewDevices.setObjectName("listViewDevices")
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.groupBoxDevices)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setGeometry(QtCore.QRect(140, 100, 91, 23))
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBoxDevices)
        self.pushButtonConnect.setGeometry(QtCore.QRect(30, 100, 91, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.groupBoxReaders = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxReaders.setGeometry(QtCore.QRect(10, 150, 269, 117))
        self.groupBoxReaders.setObjectName("groupBoxReaders")
        self.listWidgetReaders = QtWidgets.QListWidget(self.groupBoxReaders)
        self.listWidgetReaders.setGeometry(QtCore.QRect(10, 20, 251, 91))
        self.listWidgetReaders.setObjectName("listWidgetReaders")
        self.groupBoxFiles = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxFiles.setGeometry(QtCore.QRect(10, 268, 269, 199))
        self.groupBoxFiles.setObjectName("groupBoxFiles")
        self.listWidgetFiles = QtWidgets.QListWidget(self.groupBoxFiles)
        self.listWidgetFiles.setGeometry(QtCore.QRect(10, 20, 251, 171))
        self.listWidgetFiles.setObjectName("listWidgetFiles")
        self.labelAuthLevel = QtWidgets.QLabel(self.centralWidget)
        self.labelAuthLevel.setGeometry(QtCore.QRect(10, 480, 141, 16))
        self.labelAuthLevel.setObjectName("labelAuthLevel")
        self.comboBoxAuthSel = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxAuthSel.setGeometry(QtCore.QRect(166, 480, 111, 22))
        self.comboBoxAuthSel.setObjectName("comboBoxAuthSel")
        self.pushButtonRead = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonRead.setEnabled(False)
        self.pushButtonRead.setGeometry(QtCore.QRect(176, 512, 101, 31))
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.groupBoxFaceImages = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxFaceImages.setGeometry(QtCore.QRect(290, 10, 380, 257))
        self.groupBoxFaceImages.setObjectName("groupBoxFaceImages")
        self.labelFacesPic1 = QtWidgets.QLabel(self.groupBoxFaceImages)
        self.labelFacesPic1.setGeometry(QtCore.QRect(8, 20, 178, 231))
        self.labelFacesPic1.setText("")
        self.labelFacesPic1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFacesPic1.setObjectName("labelFacesPic1")
        self.labelFacesPic2 = QtWidgets.QLabel(self.groupBoxFaceImages)
        self.labelFacesPic2.setGeometry(QtCore.QRect(194, 20, 178, 231))
        self.labelFacesPic2.setText("")
        self.labelFacesPic2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFacesPic2.setObjectName("labelFacesPic2")
        self.groupBoxFingerprints = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxFingerprints.setGeometry(QtCore.QRect(680, 10, 112, 257))
        self.groupBoxFingerprints.setObjectName("groupBoxFingerprints")
        self.labelFingerprintsPic1 = QtWidgets.QLabel(self.groupBoxFingerprints)
        self.labelFingerprintsPic1.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.labelFingerprintsPic1.setText("")
        self.labelFingerprintsPic1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFingerprintsPic1.setObjectName("labelFingerprintsPic1")
        self.labelFingerprintsPic2 = QtWidgets.QLabel(self.groupBoxFingerprints)
        self.labelFingerprintsPic2.setGeometry(QtCore.QRect(10, 140, 91, 111))
        self.labelFingerprintsPic2.setText("")
        self.labelFingerprintsPic2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFingerprintsPic2.setObjectName("labelFingerprintsPic2")
        self.groupBoxSignatures = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxSignatures.setGeometry(QtCore.QRect(290, 340, 380, 127))
        self.groupBoxSignatures.setObjectName("groupBoxSignatures")
        self.labelSignPic1 = QtWidgets.QLabel(self.groupBoxSignatures)
        self.labelSignPic1.setGeometry(QtCore.QRect(10, 20, 361, 50))
        self.labelSignPic1.setText("")
        self.labelSignPic1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSignPic1.setObjectName("labelSignPic1")
        self.labelSignPic2 = QtWidgets.QLabel(self.groupBoxSignatures)
        self.labelSignPic2.setGeometry(QtCore.QRect(10, 70, 361, 50))
        self.labelSignPic2.setText("")
        self.labelSignPic2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSignPic2.setObjectName("labelSignPic2")
        self.groupBoxAuthentications = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxAuthentications.setGeometry(QtCore.QRect(680, 340, 112, 127))
        self.groupBoxAuthentications.setObjectName("groupBoxAuthentications")
        self.labelBac = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelBac.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.labelBac.setObjectName("labelBac")
        self.labelCa = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelCa.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.labelCa.setObjectName("labelCa")
        self.labelPa = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelPa.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.labelPa.setObjectName("labelPa")
        self.labelMrz = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelMrz.setGeometry(QtCore.QRect(10, 95, 31, 16))
        self.labelMrz.setObjectName("labelMrz")
        self.labelPace = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelPace.setGeometry(QtCore.QRect(60, 20, 31, 16))
        self.labelPace.setObjectName("labelPace")
        self.labelTa = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelTa.setGeometry(QtCore.QRect(60, 45, 31, 16))
        self.labelTa.setObjectName("labelTa")
        self.labelAa = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelAa.setGeometry(QtCore.QRect(60, 70, 31, 16))
        self.labelAa.setObjectName("labelAa")
        self.labelFace = QtWidgets.QLabel(self.groupBoxAuthentications)
        self.labelFace.setGeometry(QtCore.QRect(60, 95, 31, 16))
        self.labelFace.setObjectName("labelFace")
        self.textEditMsgs = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditMsgs.setGeometry(QtCore.QRect(290, 478, 503, 66))
        self.textEditMsgs.setReadOnly(True)
        self.textEditMsgs.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEditMsgs.setObjectName("textEditMsgs")
        self.textEditMrz = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditMrz.setGeometry(QtCore.QRect(290, 274, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.textEditMrz.setFont(font)
        self.textEditMrz.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEditMrz.setStyleSheet("QTextEdit {text-align: center}")
        self.textEditMrz.setAcceptRichText(False)
        self.textEditMrz.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEditMrz.setObjectName("textEditMrz")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Read Card"))
        self.groupBoxDevices.setTitle(_translate("MainWindow", "Devices"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.groupBoxReaders.setTitle(_translate("MainWindow", "Card Readers"))
        self.groupBoxFiles.setTitle(_translate("MainWindow", "Files"))
        self.labelAuthLevel.setText(_translate("MainWindow", "Authentication level:"))
        self.pushButtonRead.setText(_translate("MainWindow", "Read"))
        self.groupBoxFaceImages.setTitle(_translate("MainWindow", "Face images"))
        self.groupBoxFingerprints.setTitle(_translate("MainWindow", "Fingerprints"))
        self.groupBoxSignatures.setTitle(_translate("MainWindow", "Signatures"))
        self.groupBoxAuthentications.setTitle(_translate("MainWindow", "Authentications"))
        self.labelBac.setText(_translate("MainWindow", "BAC"))
        self.labelCa.setText(_translate("MainWindow", "CA"))
        self.labelPa.setText(_translate("MainWindow", "PA"))
        self.labelMrz.setText(_translate("MainWindow", "MRZ"))
        self.labelPace.setText(_translate("MainWindow", "PACE"))
        self.labelTa.setText(_translate("MainWindow", "TA"))
        self.labelAa.setText(_translate("MainWindow", "AA"))
        self.labelFace.setText(_translate("MainWindow", "Face"))
        self.textEditMrz.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

