from setuptools import setup, find_packages

setup(
    name="django-sorl-async-thumbnails",
    version="0.1.1",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=3.2",
        "sorl-thumbnail>=12.9.0",
        "celery>=5.0.0",
    ],
    author="Alex",
    author_email="web@2347.ru",
    description="Asynchronous thumbnail generation for sorl-thumbnail using Celery",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/alex-msk/sorl_async_thumbnails",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Framework :: Django",
        "Framework :: Django :: 3.2",
        "Framework :: Django :: 4.0",
        "Framework :: Django :: 4.1",
        "Framework :: Django :: 4.2",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
) 