from typing import Optional

def from_any_to_root(symbol: str) -> str: ...
def from_any_to_cms(symbol: str) -> str: ...
def from_any_to_cqs(symbol: str) -> str: ...
def from_any_to_nasdaq_integrated(symbol: str) -> str: ...
def from_any_to_cms_suffix(symbol: str) -> Optional[str]: ...
def from_any_to_cqs_suffix(symbol: str) -> Optional[str]: ...
def from_any_to_nasdaq_suffix(symbol: str) -> Optional[str]: ...
