# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.automation_workflow_item_kind import AutomationWorkflowItemKind


class AutomationWorkflowItemParams(typing_extensions.TypedDict):
    kind: AutomationWorkflowItemKind
    """
    The type of operation the task performs.
    """

    label: typing_extensions.NotRequired[str]
    """
    Optional label for the output of this step.
    """

    format: typing_extensions.NotRequired[str]
    """
    Output format (e.g., mp4, jpg)
    """

    width: typing_extensions.NotRequired[int]
    """
    Output width
    """

    height: typing_extensions.NotRequired[int]
    """
    Output height
    """

    resize: typing_extensions.NotRequired[str]
    """
    Resize mode
    """

    quality: typing_extensions.NotRequired[int]
    """
    Quality setting
    """
