ENGLISH_WORD_NUM = {
    "zero": 0,
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
    "thirteen": 13,
    "fourteen": 14,
    "fifteen": 15,
    "sixteen": 16,
    "seventeen": 17,
    "eighteen": 18,
    "nineteen": 19,
    "twenty": 20,
    "thirty": 30,
    "forty": 40,
    "fifty": 50,
    "sixty": 60,
    "seventy": 70,
    "eighty": 80,
    "ninety": 90,
    "hundred": 100,
    "thousand": 10 ** 3,
    "million": 10 ** 6,
    "billion": 10 ** 9,
    "trillion": 10 ** 12,
    "quadrillion": 10 ** 15,
    "quintillion": 10 ** 18,
    "sextillion": 10 ** 21,
    "septillion": 10 ** 24,
    "octillion": 10 ** 27,
    "nonillion": 10 ** 30,
    "decillion": 10 ** 33,
    "undecillion": 10 ** 36,
    "duodecillion": 10 ** 39,
    # "tredecillion": 10 ** 42,
    # "quattuordecillion": 10 ** 45,
    # "quindecillion": 10 ** 48,
    # "sexdecillion": 10 ** 51,
    # "septendecillion": 10 ** 54,
    # "octodecillion": 10 ** 57,
}

ENGLISH_NUM_WORDS = {
    "ZERO": ["zero", "hundred"],
    "UNIT": ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"],
    "TEENS": ["", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
              "nineteen"],
    "OTHERS": [""],
    "TENS": ["", "ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"],
    "THOUSANDS": ["", "thousand", "million", "billion", "trillion", "quadrillion", "quintillion", "sextillion",
                  "septillion", "octillion", "nonillion", "decillion", "undecillion", "duodecillion"],
    "POWER": [1, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39]
}
