K_NOTEBOOK = 1
K_MONITOR = 2
K_SYS_BLOCK = 3
K_MFU = 4 
K_MONO_BLOCK = 5 
K_SMARTPHONE = 6
K_TABLET = 7
K_SMART_WATCH = 8
K_WATCH = 9
K_VR = 10
K_FITNES = 11
K_E_BOOK = 12
K_ACTION_CAMERA = 13
K_FOR_GARDEN = 14
K_ELECTROTOOL = 15
K_SENSORSTOOL = 16
K_STRONG_TECH = 17
K_MACHINE = 18
K_AUDIO_TECH = 19
K_DVD = 20
K_OTH_FOR_PHOTO_VIDEO = 21
K_HOME_KINOTEATR = 22
K_MICROPHONE = 23
K_FOR_TV = 24
K_TV = 25
K_HI_FI_TECH = 26
K_CAMERA = 27
K_PROECTOR = 28
K_CAMERA_TOOLS = 29
K_VIDEOCAMERA = 30

K_SALES = -1
K_OTHERS = -2


