# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .splitter_output_splits_item import SplitterOutputSplitsItem


class SplitterOutput(UniversalBaseModel):
    splits: typing.List[SplitterOutputSplitsItem]
    is_external: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isExternal")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
