"""Constants for the pyaffalddk integration."""


GH_API = b'NDc5RDQwRjQtQjNFMS00MDM4LTkxMzAtNzY0NTMxODhDNzRD'


NON_SUPPORTED_ITEMS = [
    "Asbest",
    "Beholderudbringning",
    "Beholderservice",
    "Bestil afhentning",
    "Bestillerordning",
    "Farligt affald (skal bestilles)",
    "Farligt affald - tilmeld",
    "Haveaffald (skal bestilles)",
    "Henteordning for grene",
    "Ingen tømningsdato fundet!",
    "Skal tilmeldes",
    "Storskrald (skal bestilles)",
    "Trærødder og stammer",
]


NON_SUPPORTED_ITEMS = [
    'Asbest',
    'Beholderservice',
    'Beholderudbringning',
    'Bestil afhentning',
    'Bestillerordning',
    'Farligt affald (skal bestilles)',
    'Farligt affald - tilmeld',
    'Haveaffald (skal bestilles)',
    'Henteordning for grene',
    'Ingen tømningsdato fundet!',
    'Skal tilmeldes',
    'Storskrald (skal bestilles)',
    'Trærødder og stammer'
]


SUPPORTED_ITEMS = {
    "batterier": ["Batterier"],
    "dagrenovation": ["Dagrenovation"],
    "elektronik": ["Elektronik"],
    "farligtaffald": [
        "Farligt affald",
        "Miljøkasser",
        "Farligt Affald, Rød boks",
        "Genbrugsbilen",
    ],
    "farligtaffaldmiljoboks": [
        "Farligt affald/Miljøboks",
        "Papir og glas/dåser",
        "Miljøboks",
    ],
    "flis": [
        "Flis",
        "Flishugning",
    ],
    "genbrug": [
        'Genanvendeligt',
        'Genbrug',
        'Genbrug 240 L',
        'Genbrugshal (1 stk.)',
        'Genbrugsøer'
    ],
    "glas": [
        "Industri Genbrugeligt",
        "Glas",
    ],
    "glasplast": [
        "Glas/Plast og MDK",
    ],
    "haveaffald": [
        "Haveaff.",
        "Haveaffald, flishugning",
        "Haveaffald",
        "Trærødder og stammer",
        "Haveaffald - Frivilligt",
        "Haveaffald 140 L",
        "Frivillig Haveaffald tømmes fra mandag til onsdag",
    ],
    "jern": [
        "Jern",
        "Metal",
    ],
    "juletrae": [
        "Juletræ",
    ],
    "madaffald": [
        "Madaffald",
        "Bioposer",
        "Mad",
    ],
    "metalglas": [
        "Glas og metal",
        "Metal/glas",
        "Metal-Glas",
        "Glas/Metal",
        "Metal og Glas",
        "Glas / Metal",
    ],
    "pap": [
        "Pap",
    ],
    "papir": [
        "Papir",
        "Papir 660 L",
        "Papir // Tekstilaffald",
    ],
    "papirglas": [
        "Papir og pap/Glas",
        "Glas-papir",
        "Papir, Pap/Glas",
        "Papir & glas",
    ],
    "papirglasdaaser": [
        "Papir og glas/dåser",
    ],
    "papirmetal": [
        "Papir & Metal",
        "Papir/metal",
        "Metal/papir",
        "Papir og Metal",
        "Pap & metal",
    ],
    "pappapir": [
        "Pap/Papir",
        "Papir/Pap",
        "Papir og Pap",
        "Papir, pap og tekstilaffald",
    ],
    "pappapirglasmetal": [
        "Pap, papir, tekstil & metal og glas",
        "4delt beholder",
        "Ressourcebeholder (pap/papir og glas/metal)",
        "Papir/pap og glas/metal",
        "Plast og drikkekarton - Glas og metal",
        "Genbrug - grønt låg",
    ],
    "pappi": [
        "Plast MDK og papir",
        "PAPPI",
        "Plast/MD-karton/PP",
        "Plast/Papir",
        "Papir/Plast og kartoner",
        "Papir- Plast/Mad- og Drikkekartoner",
        "Plast og Mad- & drikkekartoner/Papir",
        "Plast, Mad- og drikkekartoner, Småt Pap og Papir",
        "Papir & Pap / Plast & MDK",
        "Plast & MD-Karton / PP",
    ],
    "plast": [
        "Plast - Obligatorisk min. 1 spand",
        "Plast",
    ],
    "plastmadkarton": [
        "Plast/MDK",
        "Plast & mad- og drikkekartoner",
        "Plast/ Mad- og drikkekartoner",
        "Plast og MDK",
        "Genbrug - blåt låg",
    ],
    "plastmdkglasmetal": [
        "Plast og drikkekarton – Glas og metal",
    ],
    "plastmetal": [
        "Plast & Metal",
        "Plast, metal & MDK 660L",
        "Plast/ Metal",
        "Plast/MDK/Metal",
        "Plast-metal",
        "Plast/Metal",
        "Plast, Metal, MDK",
    ],
    "plastmetalmadmdk": [
        "Plast/Metal/Mad- & drikkekartoner",
        "Plast, mad- og drikkekartoner og metal",
    ],
    "plastmetalpapir": [
        "Plast/Metal/Papir ",
        "Genbrugsspand - Obligatorisk min. 1 spand",
    ],
    "restaffald": [
        "Restaffald // Batterier og Småt Elektronik",
        "Industri Restaffald",
        "Rest",
    ],
    "restaffaldmadaffald": [
        "Restaffald-Madaffald",
        "Rest/mad",
        "Restaffald",
        "Rest - Mad",
        "Rest-/Madaffald",
        "Mad- og restaffald",
        "Mad/rest",
        "Rest-/madaffald",
        "Mad/Rest",
        "Mad og restaffald",
        "Mad- og restaffald",
        "Mad-/ og restaffald",
        "Rest / Mad",
        "Rest Mad",
        "Energispand - Obligatorisk min. 1 spand",
        "Rest/madaffald",
        "Energibeholder (mad/rest)",
        "Rest- og Madaffald",
    ],
    "restplast": [
        "Rest + plast/MDK",
    ],
    "storskrald": [
        "Storskrald",
        "Stort elektronik",
        "Storskrald og genbrug",
        "Pap og Storskrald",
        "Stort indbo og Indendørs træ",
    ],
    "storskraldogtekstilaffald": [
        "Storskrald og tekstilaffald",
    ],
    "tekstil": [
        "Tekstiler",
        "Standplads",
        "Tekstilaffald",
        "Miljøkasse/tekstiler",
        "Tekstil",
        "Tekstilposer (1 stk.)",
    ],
}


NON_MATERIAL_LIST = [
    'Pap bundtet, havebolig (1 stk.)'
]

MATERIAL_LIST = {
    "batterier": [
        "Batterier i pose på låg (1 stk.)",
    ],
    "dagrenovation": [
        "*140 l grøn (1 stk.)",
        "240 l. container 1 x ugentligt (12 stk.)",
        "Dag",
    ],
    "elektronik": [
        "Småt elektronik i pose på låg (1 stk.)",
    ],
    "farligtaffald": [
        "",
    ],
    "farligtaffaldmiljoboks": [
        "Farligt Affald",
        "*Miljøkasse (1 stk.)",
        "Miljøboks",
        "Miljøkasse",
        "Miljøkasse (1 stk.)",
        "Miljøskab (1 stk.)",
        "Rød kasse",
        "Rød kasse henteordning (1 stk.)",
        "Rød miljøboks",
    ],
    "flis": [
        "",
    ],
    "genbrug": [
        "Gen",
        "Gen-Skel 0-2 meter (1 stk.)",
        "Genanvendeligt",
        "Genbrug",
        "Genbrug 240 L",
        "genbrug låg i låg",
        "Genbrugshal (1 stk.)",
        "genbrugsspand",
        "Genbrugsøer",
        "Tekstiler",
    ],
    "glas": [
        "240 L glas (1 stk.)",
        "400 liter - Glas - Tømmes hver 8. uge (1 stk.)",
        "Cube 1500 L (Flasker) (1 stk.)",
        "Glas",
        "Glas, 660 liter (2 stk.)",
    ],
    "glasplast": [
        "",
    ],
    "haveaffald": [
        "Have",
        "Haveaffald",
        "Haveaffald henteordning (1 stk.)",
        "Havespand",
    ],
    "jern": [
        "240 L metal (1 stk.)",
        "240 liter - Metal - Tømmes hver 8. uge (1 stk.)",
        "Metal",
        "Metal, 660 liter (1 stk.)",
    ],
    "juletrae": [
        "Juletræ",
        "Juletræer (1 stk.)",
    ],
    "madaffald": [
        "*190 l rød (1 stk.)",
        "140 L madaffald (1 stk.)",
        "Madaffald",
        "Mad",
    ],
    "metalglas": [
        "240 L - Metal og Glas (1 stk.)",
        "240 L. Glas/Metal - 4 tømninger (1 stk.)",
        "240 l Glas/metal Egenløsning (1 stk.)",
        "240 l Glas/metal Egenløsning (Privat) (1 stk.)",
        "240 l glas/metal - 4 tømninger (1 stk.)",
        "240 liter - Metal/Glas - tømmes hver 8. uge (1 stk.)",
        "Glas & Metal",
        "Metal og Glas",
        "Glas/metal",
        "Glas/metal (1 stk.)",
        "Glas/metal, afstand over 5 meter (1 stk.)",
        "Metal/Glas 240 l - 2-kammer (1 stk.)",
        "Metal/glas 240 l (hver 12. uge) (1 stk.)",
    ],
    "pap": [
        "240 L - Pap - Skel (1 stk.)",
        "240 l Pap Egenløsning (1 stk.)",
        "240 l Pap Egenløsning (Privat) (1 stk.)",
        "400 liter - Pap og papir - Tømmes hver 2. uge (1 stk.)",
        "770 L pap (1 stk.)",
        "Beholder til pap (1 stk.)",
        "Indsamling af pap",
        "Pap",
        "Pap 240 L (1 stk.)",
        "Pap 240 L (ejer:kommune) (h) (1 stk.)",
        "Pap 240 L (villa) (1 stk.)",
        "Pap, 660 liter (3 stk.)",
        "Pap - 240 l.  (1 stk.)",
    ],
    "papir": [
        "660 L papir (1 stk.)",
        "Papir",
        "Papir, 660 liter (3 stk.)",
    ],
    "papirglas": [
        "Papir/glas - 240 l. fortovsindsamling (1 stk.)",
        "Papir og Glas",
        "Papir og pap/Glas",
    ],
    "papirglasdaaser": [
        "*240 L 2-delt Papir/glas-dåser en-familie (1 stk.)",
        "240 L 2-delt Papir/glas-dåser en-familie (1 stk.)",
    ],
    "papirglasmetalplast": [
        '240 l genbrug låg i låg (1 stk.)',
        '4-kammer (370 l) (1 stk.)',
        '4-kammer',
        'Pap og papir/metal, glas og hård plast - 240 L (1 stk.)',
        'Pap og papir/metal, glas og hård plast - 240 L (EX) (1 stk.)',
        'plast/metal/drikkekartoner og papir/pap',
        'plast/metal/MDK/papir/pap',
    ],
    "papirmetal": [
        "Metal og papir 240 L (ejer.kommune) (1 stk.)",
    ],
    "pappapir": [
        "240L papir, pap (1 stk.)",
        "Genbrugsbeholder PP-240L/6uge (1 stk.)",
        "pap/papir",
        "papir/pap",
        "Papir/Papspand",
        "papir, pap",
    ],
    "pappapirglasmetal": [
        '240 L 2-delt Papir/glas-dåser en-familie (1 stk.)',
        '240 l delt genbrug - grønt låg (1 stk.)',
        '240 l genbrug 2-kammer (2023) (1 stk.)',
        '240 liter glas/metal og pap/papir - 2 rum',
        '240L metal, glas, plast/papir gl. (1 stk.)',
        '4-kammer (240 l) (1 stk.)',
        'Glas & metal og papir & småt pap',
        'glas/metal og pap/papir',
        'pap, papir, tekstil & metal og glas',
    ],
    "pappi": [
        '240 L - Plast og Papir (1 stk.)',
        '240 L. PMDK/PP 3 ugers tømning (1 stk.)',
        '240 l PMDK/PP 3 ugers tømning (1 stk.)',
        '240 l Plast+MDK/Papir - Egenløsning (1 stk.)',
        '240 l Plast+MDK/Papir - Egenløsning (Privat) (1 stk.)',
        '240 liter - Plast, MDK, papir, pap – tømmes hver 2. uge (1 stk.)',
        '240L genbrug (1 stk.)',
        '370 l Plast+MDK/Papir - Egenløsning (1 stk.)',
        '370 l Plast+MDK/Papir - Egenløsning (Privat) (1 stk.)',
        'PMDK/PP',
        'PP/MDK-plast 240 l (hver 2. uge) (1 stk.)',
        'Papir & småt pap',
        'papir/plast og kartoner',
        'Papir/Plast og MDK 240 l - 2-kammer (1 stk.)',
        'Plast/papir',
        'Plast/papir (1 stk.)',
        'Plast/papir, afstand over 5 meter (1 stk.)',
        'Plast+MDK/Papir',
        'plast & mad- og drikkekartoner',
        "plast og papir",
    ],
    "plast": [
        "Plast",
        "Plast og MDK 240 L (ejer.kommune) (1 stk.)",
        "Plastaffald",
        "Plastaffald henteordning (1 stk.)",
        "Plast, 660 liter (2 stk.)",
    ],
    "plastmadkarton": [
        "240 l genbrug - blåt låg (1 stk.)",
        "660 L plast, mad- og drikkekartoner (1 stk.)",
        "660 liter - Plast/MDK - Tømmes hver 2. uge (1 stk.)",
        "Genbrugsbeholder PMDK/MG-240L/3uge (1 stk.)",
        "Genbrug henteordning (1 stk.)",
        "Mad- og drikkekartoner",
        "Plast og mad- & drikkekartoner",
        "PMD",
    ],
    "plastmetal": [
        "Metal og Plast",
        "Plast, småt metal & MDK - 240 l. (1 stk.)",
        "Plast/Metal",
    ],
    "plastmetalmadmdk": [
    ],
    "plastmetalpapir": [
        "*140 l grøn, 14 dags tømning (1 stk.)",
    ],
    "plastmdkglasmetal": [
        "240 L todelt genbrugsspand hver 4. uge (1 stk.)",
        "240L plast, MDK/metal, glas gl. (1 stk.)",
        "todelt genbrugsspand",
        "Genbrugsbeholder, 190 ltr (1 stk.)",
        "Genbrugsspand, 240L (2-delt) (1 stk.)",
        "plast, MDK/metal, glas",
    ],
    "restaffald": [
        "9505: 770 L restaffald uge (2 stk.)",
        "Restaffald",
    ],
    "restaffaldmadaffald": [
        "*190 l rød, 14 dags tømning (1 stk.)",
        "240 liter mad- og restaffald - 2 rum",
        "energi",
        "(M/R)",
        "Mad- og restaffald",
        "mad/rest",
        "mad/restaffald",
        "rest",
        "Rest/Mad",
        "rest/madaffald",
        "Restaffald/Madaffald",
        "Rest og Mad",
        "todelt skraldespand",
    ],
    "storskrald": [
        "Elektronik, stort metal, keramik og porcelæn (1 stk.)",
        "Møbler/indbo  (1 stk.)",
        "Pap og Storskrald",
        "Småt brændbart (1 stk.)",
        "Storskrald",
        "Storskrald (1 stk.)",
        "Storskrald - fortovsindsamling (1 stk.)",
        "Storskrald distrikt 8 (1 stk.)",
        "Storskrald enfamiliehus (1 stk.)",
        "Storskrald og genbrug",
        "Stort elektronik",
    ],
    "storskraldogtekstilaffald": [
        "",
    ],
    "tekstil": [
        "Tekstil pose (1 stk.)",
        "Tekstilaffald (1 stk.)",
        "Tekstilaffald (i lukket pose) (1 stk.)",
        "Tekstilpose 25 L (1 stk.)",
        "Tekstilpose tømning (1 stk.)",
    ],
}


ICON_LIST = {
    "batterier": "mdi:battery",
    "dagrenovation": "mdi:trash-can",
    "elektronik": "mdi:power-plug",
    "farligtaffald": "mdi:recycle",
    "farligtaffaldmiljoboks": "mdi:recycle",
    "flis": "mdi:tree",
    "genbrug": "mdi:recycle",
    "glas": "mdi:bottle-soda",
    "glasplast": "mdi:trash-can",
    "haveaffald": "mdi:leaf",
    "jern": "mdi:bucket",
    "juletrae": "mdi:pine-tree",
    "madaffald": "mdi:trash-can",
    "metal": "mdi:anvil",
    "metalglas": "mdi:glass-fragile",
    "pap": "mdi:note",
    "pappapir": "mdi:file",
    "pappapirglasmetal": "mdi:trash-can",
    "pappi": "mdi:trash-can",
    "papir": "mdi:file",
    "papirglas": "mdi:greenhouse",
    "papirglasdaaser": "mdi:trash-can",
    "papirglasmetalplast": "mdi:trash-can",
    "papirmetal": "mdi:delete-empty",
    "plast": "mdi:trash-can",
    "plastmadkarton": "mdi:trash-can",
    "plastmdkglasmetal": "mdi:trash-can",
    "plastmetal": "mdi:trash-can-outline",
    "plastmetalmadmdk": "mdi:trash-can",
    "plastmetalpapir": "mdi:trash-can",
    "restaffald": "mdi:trash-can",
    "restaffaldmadaffald": "mdi:trash-can",
    "restplast": "mdi:trash-can",
    "storskrald": "mdi:table-furniture",
    "storskraldogtekstilaffald": "mdi:table-furniture",
    "tekstil": "mdi:recycle",
}

NAME_LIST = {
    "batterier": "Batterier",
    "bioposer": "Bioposer",
    "dagrenovation": "Dagrenovation",
    "elektronik": "Elektronik",
    "farligtaffald": "Farligt affald",
    "farligtaffaldmiljoboks": "Farligt affald & Miljøboks",
    "flis": "Flis",
    "genbrug": "Genbrug",
    "glas": "Glas",
    "glasplast": "Glas, Plast & Madkartoner",
    "haveaffald": "Haveaffald",
    "jern": "Metal",
    "juletrae": "Juletræer",
    "madaffald": "Madaffald",
    "metal": "Metal",
    "metalglas": "Metal & Glas",
    "pap": "Pap",
    "pappapir": "Pap & Papir",
    "pappapirglasmetal": "Pap, Papir, Glas & Metal",
    "pappi": "Papir & Plast",
    "papir": "Papir",
    "papirglas": "Papir, Pap & Glas",
    "papirglasdaaser": "Papir, Glas & Dåser",
    "papirglasmetalplast": "Papir, Glas, Metal & Plast",
    "papirmetal": "Papir & Metal",
    "plast": "Plast",
    "plastmadkarton": "Plast & Madkarton",
    "plastmdkglasmetal": "Plast, Madkarton, Glas & Metal",
    "plastmetal": "Plast & Metal",
    "plastmetalmadmdk": "Plast, Metal, Mad & Drikkekartoner",
    "plastmetalpapir": "Plast, Metal & Papir",
    "restaffald": "Restaffald",
    "restaffaldmadaffald": "Rest & Madaffald",
    "restplast": "Restaffald & Plast/Madkartoner",
    "storskrald": "Storskrald",
    "storskraldogtekstilaffald": "Storskrald & Tekstilaffald",
    "tekstil": "Tekstilaffald",
}

NAME_ARRAY = list(NAME_LIST.keys())
PAR_EXCEPTIONS = ['M/R']
STRIPS = [
        '140l ', '140 l ', '190l ', '190 l ',
        '240l ', '240 l ', '240 l.', '(240 l)', '240 liter', ', 240l', ' 240 ltr',
        '370 l ', '370 liter ',
        '14. dags tømning', '14 dages tømning', '14-dags', '14 dags tømning', '14. dage skel', 'med 14-dages tømning ved helårshuse',
        'todelt 4 ugers tømning', 'todelt 14 dages tøm', '3 ugers tømning', 'hver 4. uge', '4-ugers', 'hver 6. uge', '2 delt',
        'sommerhustømning', 'henteordning', 'beholder til', ' beh.', '1-kammer ', '2-kammer ', '1-rums',
        'egenløsning', 'distrikt 2', 'distrikt E', ' D1 ', ' gl.', 'sommer 32', 'm. sommertømning',
        '-skel 0-2 meter', '- Stand', '- Skel',
]
ODD_EVEN_ARRAY = ["lige", "ulige"]
WEEKDAYS = ["Mandag", "Tirsdag", "Onsdag",
            "Torsdag", "Fredag", "Lørdag", "Søndag"]
WEEKDAYS_SHORT = ["Man", "Tir", "Ons", "Tor", "Fre", "Lør", "Søn"]