# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from gumletrestapis.api_helper import APIHelper


class Input4(object):

    """Implementation of the 'Input4' model.

    Attributes:
        resolution (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "resolution": 'resolution'
    }

    _optionals = [
        'resolution',
    ]

    def __init__(self,
                 resolution=APIHelper.SKIP):
        """Constructor for the Input4 class"""

        # Initialize members of the class
        if resolution is not APIHelper.SKIP:
            self.resolution = resolution 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        resolution = dictionary.get("resolution") if dictionary.get("resolution") else APIHelper.SKIP
        # Return an object of this model
        return cls(resolution)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'resolution={(self.resolution if hasattr(self, "resolution") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'resolution={(self.resolution if hasattr(self, "resolution") else None)!s})')
