# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from gumletrestapis.api_helper import APIHelper
from gumletrestapis.models.top_asset import TopAsset


class VideoAnalyticsResponse(object):

    """Implementation of the 'Video Analytics Response' model.

    Attributes:
        top_assets (List[TopAsset]): The model property of type List[TopAsset].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "top_assets": 'top_assets'
    }

    _optionals = [
        'top_assets',
    ]

    def __init__(self,
                 top_assets=APIHelper.SKIP):
        """Constructor for the VideoAnalyticsResponse class"""

        # Initialize members of the class
        if top_assets is not APIHelper.SKIP:
            self.top_assets = top_assets 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        top_assets = None
        if dictionary.get('top_assets') is not None:
            top_assets = [TopAsset.from_dictionary(x) for x in dictionary.get('top_assets')]
        else:
            top_assets = APIHelper.SKIP
        # Return an object of this model
        return cls(top_assets)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'top_assets={(self.top_assets if hasattr(self, "top_assets") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'top_assets={(self.top_assets if hasattr(self, "top_assets") else None)!s})')
