"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .reserve import Reserve, ReserveTypedDict
from compass_api_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SwapBorrowRateTypedDict(TypedDict):
    borrow_rate_mode_from: str
    borrow_rate_mode_to: str
    variable_borrow_rate: str
    stable_borrow_rate: str
    reserve: ReserveTypedDict


class SwapBorrowRate(BaseModel):
    borrow_rate_mode_from: Annotated[str, pydantic.Field(alias="borrowRateModeFrom")]

    borrow_rate_mode_to: Annotated[str, pydantic.Field(alias="borrowRateModeTo")]

    variable_borrow_rate: Annotated[str, pydantic.Field(alias="variableBorrowRate")]

    stable_borrow_rate: Annotated[str, pydantic.Field(alias="stableBorrowRate")]

    reserve: Reserve
