
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-13T20:25:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cc9c48cfb022f5fb08af934f070e35d03f2b368",
 "version": "0+untagged.73.g0cc9c48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
