PYTHONPATH_ENV_VAR: str = "PYTHONPATH"
PINAXAI_RUNTIME_ENV_VAR: str = "PINAXAI_RUNTIME"
PINAXAI_API_KEY_ENV_VAR: str = "PINAXAI_API_KEY"

WORKSPACE_ID_ENV_VAR: str = "PINAXAI_WORKSPACE_ID"
WORKSPACE_NAME_ENV_VAR: str = "PINAXAI_WORKSPACE_NAME"
WORKSPACE_ROOT_ENV_VAR: str = "PINAXAI_WORKSPACE_ROOT"
WORKSPACE_DIR_ENV_VAR: str = "PINAXAI_WORKSPACE_DIR"
REQUIREMENTS_FILE_PATH_ENV_VAR: str = "REQUIREMENTS_FILE_PATH"

AWS_REGION_ENV_VAR: str = "AWS_REGION"
AWS_DEFAULT_REGION_ENV_VAR: str = "AWS_DEFAULT_REGION"
AWS_PROFILE_ENV_VAR: str = "AWS_PROFILE"
