#                              .......''.....                                                  
#                             ..',<?[[]+l'..                                                   
#                         .....~|t/\t/fft\?:... ...    ............  ........                  
#                       ......,uxjtjftf\ffff}I'..............................                  
#                          ....I/vxfffffjjrjt/)>"......';>?}{1)){{]-~<!I"'.'                   
#                            ..'.,~]}}1((1{1)\/t(_,..^+\/\(|(\\/tffjjt//|(~'.                  
#                                 ....'',I>-})}[}1{!i(/(((\\\///\|()1}?+>l"'.                  
#                                    .......`tznj\{})\1\||\|){[-~>iI^'.......                  
#                                    .........~uJUYcxtt|/(?i,'........ . ....                  
#                                           ...`(ruur\?>,'.....                                
#                                          .....>t/]>'... ... .                                
#                                           ...':/]~'.... ...                                  
#                                           ...."[>".....                                      
#                                          .....;_l'.....                                      
#                                           ....;~;'.....                                      
#                                           ....I>:......                                      
#                                           ....I>:......                                      
#                                           ....l-i...                                         
#                                           ...'i+!`........                                   
#                                           ....i]~'I?nLYu~'...                                
#                                    ... .......>/JdkQbbhohc:'.                                
#                                    ...'';-Qh0Qqkao*hokd&*a\`'                                
#                             .`_?xuX00mao*h*o#*#qod#ao*hhMkdfj[lI'.........                   
#                       ..'^`';v#ohhdphhkaoMhkadkoWaM*M&&*khbdpbdU/;l.......                   
#                 ..... .!CMhkoka*W##M&8W#WW##*oahaWohM#oaMW#*aahdhhkYn0nri.                   
#                 .'lfjnO*#W&M#&Mob*&#MMb0*M#ba*#MboMoW&*oaahao#o&M#ook*bamI.                  
#              .'l/Lh*ao*Mo##a##o#o#&&&8&&#8&*h**&M##8W8#M*ahoao#8oo%&oohka0UUx}:`....         
#           ...!JaM*oMoaaoa*M#hooMMB&8WMMM#8&WM#M&&MkM*#88%8WMokaoo*hhaah*M#ha*obp}'.....      
#           `fJoakMo#kM##MoMW&MM*oM*#WM#MBWB&WW&&W&W#8M#&#oWWWMW8#*Woo*hMoaoMokJh**bXOX)!      
#    ....';[Z#MMM&W##o#a#**&MW#M&8&8&M8WW8M*oMWM8W8WM#&#&&&8&#oW&&#Moao#aaohko*#*oooaohkk|^'   
# .'^_x}cb&M##M##Whdbo*MW##M&WMoWWWMMM##*##MMM#MWWM#WMMMMW&&%M##WW8&W&*#&#oMWWM###**k&k*#kodY)'
#
# Ain't fan!