FRENCH_WORD_NUM = {
    "zéro": 0,
    "un": 1,
    "deux": 2,
    "trois": 3,
    "quatre": 4,
    "cinq": 5,
    "six": 6,
    "sept": 7,
    "huit": 8,
    "neuf": 9,
    "dix": 10,
    "onze": 11,
    "douze": 12,
    "treize": 13,
    "quatorze": 14,
    "quinze": 15,
    "seize": 16,
    "dix-sept": 17,
    "dix-huit": 18,
    "dix-neuf": 19,
    "vingt": 20,
    "trente": 30,
    "quarante": 40,
    "cinquante": 50,
    "soixante": 60,
    "soixante-dix": 70,
    "quatre-vingts": 80,
    "quatre-vingt-dix": 90,
    "cent": 100,
    "mille": 10 ** 3,
    "million": 10 ** 6,
    "milliard": 10 ** 9,
    "billion": 10 ** 12,
    "billiard": 10 ** 15,
    "trillion": 10 ** 18,
    "trilliard": 10 ** 21,
    "quadrillion": 10 ** 24,
    "quadrilliard": 10 ** 27,
    "quintillion": 10 ** 30,
    "quintilliard": 10 ** 33,
    "sextillion": 10 ** 36,
    "sextilliard": 10 ** 39
}

FRENCH_NUM_WORDS = {
    "ZERO": ["zéro", "cent"],
    "UNIT": ["", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf"],
    "TEENS": ["", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf"],
    "TENS": ["", "dix", "vingt", "trente", "quarante", "cinquante", "soixante", "soixante-dix", "quatre-vingt",
             "quatre-vingt-dix"],
    "THOUSANDS": [
        "", "mille", "million", "milliard", "billion", "billiard", "trillion", "trilliard",
        "quadrillion", "quadrilliard", "quintillion", "quintilliard", "sextillion", "sextilliard"
    ],
    "OTHERS": [""],
    "POWER": [1, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39]
}
