/* tslint:disable */
/* eslint-disable */
/**
 * elkar-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnpaginatedOutputAgentOutputRecordsInner
 */
export interface UnpaginatedOutputAgentOutputRecordsInner {
    /**
     * 
     * @type {string}
     * @memberof UnpaginatedOutputAgentOutputRecordsInner
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof UnpaginatedOutputAgentOutputRecordsInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnpaginatedOutputAgentOutputRecordsInner
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof UnpaginatedOutputAgentOutputRecordsInner
     */
    isDeleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof UnpaginatedOutputAgentOutputRecordsInner
     */
    name: string;
}

/**
 * Check if a given object implements the UnpaginatedOutputAgentOutputRecordsInner interface.
 */
export function instanceOfUnpaginatedOutputAgentOutputRecordsInner(value: object): value is UnpaginatedOutputAgentOutputRecordsInner {
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isDeleted' in value) || value['isDeleted'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UnpaginatedOutputAgentOutputRecordsInnerFromJSON(json: any): UnpaginatedOutputAgentOutputRecordsInner {
    return UnpaginatedOutputAgentOutputRecordsInnerFromJSONTyped(json, false);
}

export function UnpaginatedOutputAgentOutputRecordsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnpaginatedOutputAgentOutputRecordsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'isDeleted': json['is_deleted'],
        'name': json['name'],
    };
}

export function UnpaginatedOutputAgentOutputRecordsInnerToJSON(json: any): UnpaginatedOutputAgentOutputRecordsInner {
    return UnpaginatedOutputAgentOutputRecordsInnerToJSONTyped(json, false);
}

export function UnpaginatedOutputAgentOutputRecordsInnerToJSONTyped(value?: UnpaginatedOutputAgentOutputRecordsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'description': value['description'],
        'id': value['id'],
        'is_deleted': value['isDeleted'],
        'name': value['name'],
    };
}

