# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_download_image download_image'] = 'image downloaded'

snapshots['test_find_store store_info'] = {
    'has_24h_delivery': 'bool',
    'has_delivery': 'bool',
    'sap_code': 'str',
    'shop_address': 'str',
    'store_city': 'str'
}

snapshots['test_get_config get_config'] = {
    '11': 'str',
    '13': 'str',
    '15': 'str',
    '292929': 'str',
    'AD_TOOLTIP_CLOSING_TIME': 'str',
    'CASHBACK_LINK': 'str',
    'CATALOG_SERVER_URL': 'str',
    'CDN_SERVICE_URL': 'str',
    'CHAT_URL': 'str',
    'CI': 'str',
    'CITA_SERVER_URL': 'str',
    'CI_API_V4_URL': 'str',
    'CI_BUILDS_DIR': 'str',
    'CI_BUILD_BEFORE_SHA': 'str',
    'CI_BUILD_ID': 'str',
    'CI_BUILD_NAME': 'str',
    'CI_BUILD_REF': 'str',
    'CI_BUILD_REF_NAME': 'str',
    'CI_BUILD_REF_SLUG': 'str',
    'CI_BUILD_STAGE': 'str',
    'CI_BUILD_TAG': 'str',
    'CI_BUILD_TOKEN': 'str',
    'CI_COMMIT_AUTHOR': 'str',
    'CI_COMMIT_BEFORE_SHA': 'str',
    'CI_COMMIT_DESCRIPTION': 'str',
    'CI_COMMIT_MESSAGE': 'str',
    'CI_COMMIT_REF_NAME': 'str',
    'CI_COMMIT_REF_PROTECTED': 'str',
    'CI_COMMIT_REF_SLUG': 'str',
    'CI_COMMIT_SHA': 'str',
    'CI_COMMIT_SHORT_SHA': 'str',
    'CI_COMMIT_TAG': 'str',
    'CI_COMMIT_TIMESTAMP': 'str',
    'CI_COMMIT_TITLE': 'str',
    'CI_CONCURRENT_ID': 'str',
    'CI_CONCURRENT_PROJECT_ID': 'str',
    'CI_CONFIG_PATH': 'str',
    'CI_DEFAULT_BRANCH': 'str',
    'CI_DISPOSABLE_ENVIRONMENT': 'str',
    'CI_JOB_ID': 'str',
    'CI_JOB_IMAGE': 'str',
    'CI_JOB_JWT': 'str',
    'CI_JOB_JWT_V1': 'str',
    'CI_JOB_JWT_V2': 'str',
    'CI_JOB_NAME': 'str',
    'CI_JOB_STAGE': 'str',
    'CI_JOB_STARTED_AT': 'str',
    'CI_JOB_STATUS': 'str',
    'CI_JOB_TOKEN': 'str',
    'CI_JOB_URL': 'str',
    'CI_NODE_TOTAL': 'str',
    'CI_PAGES_DOMAIN': 'str',
    'CI_PAGES_URL': 'str',
    'CI_PIPELINE_CREATED_AT': 'str',
    'CI_PIPELINE_ID': 'str',
    'CI_PIPELINE_IID': 'str',
    'CI_PIPELINE_SOURCE': 'str',
    'CI_PIPELINE_URL': 'str',
    'CI_PROJECT_CLASSIFICATION_LABEL': 'str',
    'CI_PROJECT_DESCRIPTION': 'str',
    'CI_PROJECT_DIR': 'str',
    'CI_PROJECT_ID': 'str',
    'CI_PROJECT_NAME': 'str',
    'CI_PROJECT_NAMESPACE': 'str',
    'CI_PROJECT_PATH': 'str',
    'CI_PROJECT_PATH_SLUG': 'str',
    'CI_PROJECT_REPOSITORY_LANGUAGES': 'str',
    'CI_PROJECT_ROOT_NAMESPACE': 'str',
    'CI_PROJECT_TITLE': 'str',
    'CI_PROJECT_URL': 'str',
    'CI_PROJECT_VISIBILITY': 'str',
    'CI_REGISTRY_PASSWORD': 'str',
    'CI_REGISTRY_USER': 'str',
    'CI_REPOSITORY_URL': 'str',
    'CI_RUNNER_DESCRIPTION': 'str',
    'CI_RUNNER_EXECUTABLE_ARCH': 'str',
    'CI_RUNNER_ID': 'str',
    'CI_RUNNER_REVISION': 'str',
    'CI_RUNNER_SHORT_TOKEN': 'str',
    'CI_RUNNER_VERSION': 'str',
    'CI_SERVER': 'str',
    'CI_SERVER_HOST': 'str',
    'CI_SERVER_NAME': 'str',
    'CI_SERVER_PORT': 'str',
    'CI_SERVER_PROTOCOL': 'str',
    'CI_SERVER_REVISION': 'str',
    'CI_SERVER_TLS_CA_FILE': 'str',
    'CI_SERVER_URL': 'str',
    'CI_SERVER_VERSION': 'str',
    'CI_SERVER_VERSION_MAJOR': 'str',
    'CI_SERVER_VERSION_MINOR': 'str',
    'CI_SERVER_VERSION_PATCH': 'str',
    'CI_TEMPLATE_REGISTRY_HOST': 'str',
    'DEFAULT_STORE_ADDRESS': 'str',
    'DEFAULT_STORE_ID': 'str',
    'DEFAULT_STORE_LAT': 'str',
    'DEFAULT_STORE_LON': 'str',
    'DELAY_AFTER_PAY_IN_MS': 'str',
    'DISABLED_INDEX': 'str',
    'DOCKER_REGISTRY': 'str',
    'DOCKER_REGISTRY_PASSWORD': 'str',
    'DOCKER_REGISTRY_USER': 'str',
    'ENV_FILE': 'str',
    'ENV_NAME': 'str',
    'FAQ_SERVER_URL': 'str',
    'FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION': 'str',
    'FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR': 'str',
    'FF_ENABLE_BASH_EXIT_CODE_CHECK': 'str',
    'FF_ENABLE_JOB_CLEANUP': 'str',
    'FF_KUBERNETES_HONOR_ENTRYPOINT': 'str',
    'FF_NETWORK_PER_BUILD': 'str',
    'FF_POSIXLY_CORRECT_ESCAPES': 'str',
    'FF_SCRIPT_SECTIONS': 'str',
    'FF_SKIP_NOOP_BUILD_STAGES': 'str',
    'FF_USE_DIRECT_DOWNLOAD': 'str',
    'FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL': 'str',
    'FF_USE_FASTZIP': 'str',
    'FF_USE_IMPROVED_URL_MASKING': 'str',
    'FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY': 'str',
    'FF_USE_NEW_BASH_EVAL_STRATEGY': 'str',
    'FF_USE_NEW_SHELL_ESCAPE': 'str',
    'FF_USE_POWERSHELL_PATH_RESOLVER': 'str',
    'FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY': 'str',
    'FIVED_SERVER_URL': 'str',
    'FOOTER_HOSTING_DOCS': 'str',
    'FOOTER_LINK_FEEDBACK': 'str',
    'GITLAB_CI': 'str',
    'GITLAB_FEATURES': 'str',
    'GITLAB_GITLAB_RUNNER_PORT': 'str',
    'GITLAB_GITLAB_RUNNER_PORT_9252_TCP': 'str',
    'GITLAB_GITLAB_RUNNER_PORT_9252_TCP_ADDR': 'str',
    'GITLAB_GITLAB_RUNNER_PORT_9252_TCP_PORT': 'str',
    'GITLAB_GITLAB_RUNNER_PORT_9252_TCP_PROTO': 'str',
    'GITLAB_GITLAB_RUNNER_SERVICE_HOST': 'str',
    'GITLAB_GITLAB_RUNNER_SERVICE_PORT': 'str',
    'GITLAB_GITLAB_RUNNER_SERVICE_PORT_METRICS': 'str',
    'GITLAB_RUNNER_REGISTRATION_TOKEN': 'str',
    'GITLAB_TOKEN': 'str',
    'GITLAB_USER_EMAIL': 'str',
    'GITLAB_USER_ID': 'str',
    'GITLAB_USER_LOGIN': 'str',
    'GITLAB_USER_NAME': 'str',
    'GIT_SUBMODULE_FORCE_HTTPS': 'str',
    'HELM_REGISTRY': 'str',
    'HELM_REGISTRY_TOKEN': 'str',
    'HELM_REPO_PASSWORD': 'str',
    'HELM_REPO_URL': 'str',
    'HELM_REPO_USERNAME': 'str',
    'HELPLINE_CONTACT_NUMBER': 'str',
    'HOME': 'str',
    'HOST': 'str',
    'HOSTNAME': 'str',
    'INIT_CWD': 'str',
    'K8S_DEV_CONFIG': 'str',
    'K8S_KUBECONFIG_DEV': 'str',
    'K8S_KUBECONFIG_PROD': 'str',
    'K8S_PROD02_CONFIG': 'str',
    'K8S_PROD_CONFIG': 'str',
    'K8S_PROD_SITE5KA_CONFIG': 'str',
    'K8S_TEST02_CONFIG': 'str',
    'K8S_TEST_CONFIG': 'str',
    'K8S_X5M_COMMON_BACKEND_DEV_CONFIG': 'str',
    'K8S_X5M_PHYGITAL_DEV_CONFIG': 'str',
    'KE_INFO_SYS': 'str',
    'KLAD_LINK': 'str',
    'KUBERNETES_PORT': 'str',
    'KUBERNETES_PORT_443_TCP': 'str',
    'KUBERNETES_PORT_443_TCP_ADDR': 'str',
    'KUBERNETES_PORT_443_TCP_PORT': 'str',
    'KUBERNETES_PORT_443_TCP_PROTO': 'str',
    'KUBERNETES_SERVICE_HOST': 'str',
    'KUBERNETES_SERVICE_PORT': 'str',
    'KUBERNETES_SERVICE_PORT_HTTPS': 'str',
    'LOYALTY_CASH_TIMER': 'str',
    'LOYALTY_LINK_ACTIVATE_CARD': 'str',
    'LOYALTY_LINK_CREATE_CARD': 'str',
    'LY_SERVER_URL': 'str',
    'MILKA_LINK': 'str',
    'MYSTERY_SHOPPER_LINK': 'str',
    'Merchant': 'str',
    'NEWS_SERVER_URL': 'str',
    'NODE': 'str',
    'NODE_VERSION': 'str',
    'OFFERHUB_BASE_URL': 'str',
    'OLDPWD': 'str',
    'ORDER_CONTACT_NUMBER': 'str',
    'ORDER_FEEDBACK_PHONE': 'str',
    'ORDER_SERVER_URL': 'str',
    'PACKAGE': 'str',
    'PACKET_LINK': 'str',
    'PAGE_NOT_FOUND_URL': 'str',
    'PARTICIPANT_LINK': 'str',
    'PARTICIPATE_LINK': 'str',
    'PARTICIPATE_LINK_IMG_PRE': 'str',
    'PATH': 'str',
    'PRODUCT_SELECTION_CATEGORY_ID': 'str',
    'PRODUCT_SELECTION_URL': 'str',
    'PROMOCODE_RULES': 'str',
    'PWD': 'str',
    'PYPI_REPO_PASSWORD': 'str',
    'PYPI_REPO_URL': 'str',
    'PYPI_REPO_USERNAME': 'str',
    'PayWithPoints': 'str',
    'QUERY_LIMIT_DESKTOP': 'str',
    'QUERY_LIMIT_PORTABLE': 'str',
    'QUERY_MAX_LIMIT': 'str',
    'REACT_APP_BANK_CARD': 'str',
    'REACT_APP_DESKTOP_APP_APPLE': 'str',
    'REACT_APP_DESKTOP_APP_GOOGLE': 'str',
    'REACT_APP_DESKTOP_APP_HUAWEI': 'str',
    'REACT_APP_KEYCLOAK_CLIENT_ID': 'str',
    'REACT_APP_KEYCLOAK_REALM': 'str',
    'REACT_APP_KEYCLOAK_URL': 'str',
    'REACT_APP_MOBILE_APP': 'str',
    'REACT_APP_PERSONAL_INFO': 'str',
    'REFETCH_INTERVAL_ALL_ORDERS': 'str',
    'REFETCH_INTERVAL_INCREMENT': 'str',
    'REFETCH_INTERVAL_MAX': 'str',
    'REFETCH_INTERVAL_MIN': 'str',
    'REFETCH_INTERVAL_WAITING_FOR_PAY': 'str',
    'REFETCH_LIMIT': 'str',
    'RETRY_TIME': 'str',
    'SBERPAYBACKDEEPLINK': 'str',
    'SBPBACKDEEPLINK': 'str',
    'SCM_X5M_ACCESS_TOKEN': 'str',
    'SDK_URL': 'str',
    'SDK_USER_ID_TYPE': 'str',
    'SENTRY_DSN': 'str',
    'SHLVL': 'str',
    'SHOW_ADFOX_KING_BANNER': 'str',
    'SHOW_PACKET_BANNER': 'str',
    'SITE5KA_SENTRY_AUTH_TOKEN': 'str',
    'SITE5KA_SENTRY_ORG': 'str',
    'SITE5KA_SENTRY_PROJECT': 'str',
    'SITEMAP_FILE': 'str',
    'SONAR_HOST': 'str',
    'SONAR_LOGIN': 'str',
    'SONAR_PROTOCOL': 'str',
    'SONAR_TAG': 'str',
    'SUPPORT_UTL': 'str',
    'TAG': 'str',
    'TEMPORARY_BANNERS_URL': 'str',
    'TIMEOUT': 'str',
    'TIMEOUT_LY': 'str',
    'TYPE': 'str',
    'URL_TRAILING_SLASH': 'str',
    'USE_OFFLINE': 'str',
    'VAULT_ADDR': 'str',
    'VAULT_AUTH_PATH': 'str',
    'VAULT_AUTH_ROLE': 'str',
    'VAULT_SERVER_URL': 'str',
    'VERSION': 'str',
    'X5_ACTION_EVENT_URL': 'str',
    'X5_ACTION_SEND_EVENT_HEATLHCHECK_ENDPOINT_URL': 'str',
    'X5_SENTRY_URL': 'str',
    'YANDEX_MAP_API_KEY_GEOCODE': 'str',
    'YANDEX_MAP_API_KEY_SUGGEST': 'str',
    'YANDEX_MAP_API_QUERY_DEBOUNCE': 'str',
    'YANDEX_METRIC_COUNTER_ID': 'str',
    'YARN_VERSION': 'str',
    'YARN_WRAP_OUTPUT': 'str',
    '_': 'str',
    'a': [
    ],
    'address': {
    },
    'align': 'str',
    'alignItems': 'str',
    'alignSelf': 'str',
    'appearance': 'str',
    'background': 'str',
    'backgroundColor': 'str',
    'barcode': 'str',
    'base': 'str',
    'baseStyle': {
    },
    'bg': 'str',
    'border': 'str',
    'borderBottomWidth': 'str',
    'borderColor': 'str',
    'borderLeftWidth': 'str',
    'borderRadius': 'str',
    'borderTopLeftRadius': 'str',
    'borderTopRadius': 'str',
    'boxShadow': 'str',
    'c157f7': 'str',
    'cardNo': 'str',
    'children': [
    ],
    'className': 'str',
    'color': 'str',
    'colorScheme': 'str',
    'config': {
    },
    'cx': 'str',
    'cy': 'str',
    'd': 'str',
    'direction': 'str',
    'display': 'str',
    'e': [
    ],
    'emptyColor': 'str',
    'f2483c': 'str',
    'f4efe4': 'str',
    'ffa500': 'str',
    'fill': 'str',
    'flex': 'str',
    'flexDirection': 'str',
    'focusable': 'str',
    'fontSize': 'str',
    'fontWeight': 'str',
    'gap': 'str',
    'geocode': 'str',
    'get': 'str',
    'getBalance': 'str',
    'getBanners': 'str',
    'getBarcode': 'str',
    'getCards': 'str',
    'getCategoriesData': 'str',
    'getNews': 'str',
    'getOrders': 'str',
    'getProduct': 'str',
    'getProductSelection': 'str',
    'getPromoOffers': 'str',
    'getShops': 'str',
    'getStoreByCoordinates': 'str',
    'getStoreBySapCode': 'str',
    'h': 'str',
    'height': 'str',
    'hookName': 'str',
    'image': 'str',
    'justifyContent': 'str',
    'lg': 'str',
    'lineHeight': 'str',
    'main': 'str',
    'margin': 'str',
    'marginBottom': 'str',
    'marginTop': 'str',
    'maxHeight': 'str',
    'maxWidth': 'str',
    'md': 'str',
    'minHeight': 'str',
    'name': 'str',
    'npm_config_bin_links': 'str',
    'npm_config_ignore_optional': 'str',
    'npm_config_ignore_scripts': 'str',
    'npm_config_init_license': 'str',
    'npm_config_init_version': 'str',
    'npm_config_registry': 'str',
    'npm_config_save_prefix': 'str',
    'npm_config_strict_ssl': 'str',
    'npm_config_user_agent': 'str',
    'npm_config_version': 'str',
    'npm_config_version_commit_hooks': 'str',
    'npm_config_version_git_message': 'str',
    'npm_config_version_git_sign': 'str',
    'npm_config_version_git_tag': 'str',
    'npm_config_version_tag_prefix': 'str',
    'npm_execpath': 'str',
    'npm_lifecycle_event': 'str',
    'npm_lifecycle_script': 'str',
    'npm_node_execpath': 'str',
    'npm_package_dependencies__loadable_component': 'str',
    'npm_package_dependencies__orama_orama': 'str',
    'npm_package_dependencies__react_keycloak_web': 'str',
    'npm_package_dependencies__sber_ecom_core_sberpay_widget': 'str',
    'npm_package_dependencies__sentry_react': 'str',
    'npm_package_dependencies__types_jwt_decode': 'str',
    'npm_package_dependencies_axios': 'str',
    'npm_package_dependencies_bwip_js': 'str',
    'npm_package_dependencies_classnames': 'str',
    'npm_package_dependencies_date_fns': 'str',
    'npm_package_dependencies_dompurify': 'str',
    'npm_package_dependencies_dotenv': 'str',
    'npm_package_dependencies_keycloak_js': 'str',
    'npm_package_dependencies_mobx': 'str',
    'npm_package_dependencies_mobx_react_lite': 'str',
    'npm_package_dependencies_qr_code_styling': 'str',
    'npm_package_dependencies_react': 'str',
    'npm_package_dependencies_react_dom': 'str',
    'npm_package_dependencies_react_helmet_async': 'str',
    'npm_package_dependencies_react_intersection_observer': 'str',
    'npm_package_dependencies_react_query': 'str',
    'npm_package_dependencies_react_router_dom': 'str',
    'npm_package_dependencies_react_yandex_maps': 'str',
    'npm_package_dependencies_react_yandex_metrika': 'str',
    'npm_package_dependencies_swiper': 'str',
    'npm_package_dependencies_uuid': 'str',
    'npm_package_dependencies_virtua': 'str',
    'npm_package_devDependencies__babel_core': 'str',
    'npm_package_devDependencies__babel_plugin_transform_typescript': 'str',
    'npm_package_devDependencies__babel_preset_env': 'str',
    'npm_package_devDependencies__babel_preset_react': 'str',
    'npm_package_devDependencies__babel_preset_typescript': 'str',
    'npm_package_devDependencies__chakra_ui_react': 'str',
    'npm_package_devDependencies__chromatic_com_storybook': 'str',
    'npm_package_devDependencies__emotion_react': 'str',
    'npm_package_devDependencies__emotion_styled': 'str',
    'npm_package_devDependencies__eslint_js': 'str',
    'npm_package_devDependencies__pmmmwh_react_refresh_webpack_plugin': 'str',
    'npm_package_devDependencies__storybook_addon_essentials': 'str',
    'npm_package_devDependencies__storybook_addon_interactions': 'str',
    'npm_package_devDependencies__storybook_addon_links': 'str',
    'npm_package_devDependencies__storybook_addon_onboarding': 'str',
    'npm_package_devDependencies__storybook_addon_webpack5_compiler_babel': 'str',
    'npm_package_devDependencies__storybook_addon_webpack5_compiler_swc': 'str',
    'npm_package_devDependencies__storybook_react_webpack5': 'str',
    'npm_package_devDependencies__svgr_webpack': 'str',
    'npm_package_devDependencies__swc_cli': 'str',
    'npm_package_devDependencies__swc_core': 'str',
    'npm_package_devDependencies__types_babel__core': 'str',
    'npm_package_devDependencies__types_babel__preset_env': 'str',
    'npm_package_devDependencies__types_dompurify': 'str',
    'npm_package_devDependencies__types_dotenv_webpack': 'str',
    'npm_package_devDependencies__types_eslint': 'str',
    'npm_package_devDependencies__types_html_webpack_plugin': 'str',
    'npm_package_devDependencies__types_loadable__component': 'str',
    'npm_package_devDependencies__types_node': 'str',
    'npm_package_devDependencies__types_react': 'str',
    'npm_package_devDependencies__types_react_dom': 'str',
    'npm_package_devDependencies__types_webpack': 'str',
    'npm_package_devDependencies__types_webpack_dev_server': 'str',
    'npm_package_devDependencies__typescript_eslint_eslint_plugin': 'str',
    'npm_package_devDependencies__typescript_eslint_parser': 'str',
    'npm_package_devDependencies__webpack_cli_serve': 'str',
    'npm_package_devDependencies_babel_loader': 'str',
    'npm_package_devDependencies_babel_preset_airbnb': 'str',
    'npm_package_devDependencies_clean_webpack_plugin': 'str',
    'npm_package_devDependencies_copy_webpack_plugin': 'str',
    'npm_package_devDependencies_css_loader': 'str',
    'npm_package_devDependencies_css_minimizer_webpack_plugin': 'str',
    'npm_package_devDependencies_eslint': 'str',
    'npm_package_devDependencies_eslint_config_airbnb': 'str',
    'npm_package_devDependencies_eslint_config_airbnb_base': 'str',
    'npm_package_devDependencies_eslint_config_airbnb_typescript': 'str',
    'npm_package_devDependencies_eslint_config_prettier': 'str',
    'npm_package_devDependencies_eslint_config_standard_with_typescript': 'str',
    'npm_package_devDependencies_eslint_config_xo': 'str',
    'npm_package_devDependencies_eslint_config_xo_typescript': 'str',
    'npm_package_devDependencies_eslint_import_resolver_typescript': 'str',
    'npm_package_devDependencies_eslint_plugin_import': 'str',
    'npm_package_devDependencies_eslint_plugin_n': 'str',
    'npm_package_devDependencies_eslint_plugin_prettier': 'str',
    'npm_package_devDependencies_eslint_plugin_promise': 'str',
    'npm_package_devDependencies_eslint_plugin_react': 'str',
    'npm_package_devDependencies_eslint_plugin_react_hooks': 'str',
    'npm_package_devDependencies_eslint_plugin_react_refresh': 'str',
    'npm_package_devDependencies_framer_motion': 'str',
    'npm_package_devDependencies_globals': 'str',
    'npm_package_devDependencies_html_webpack_plugin': 'str',
    'npm_package_devDependencies_husky': 'str',
    'npm_package_devDependencies_init': 'str',
    'npm_package_devDependencies_lint_staged': 'str',
    'npm_package_devDependencies_lodash_debounce': 'str',
    'npm_package_devDependencies_mini_css_extract_plugin': 'str',
    'npm_package_devDependencies_prettier': 'str',
    'npm_package_devDependencies_react_refresh': 'str',
    'npm_package_devDependencies_sass': 'str',
    'npm_package_devDependencies_sass_loader': 'str',
    'npm_package_devDependencies_sitemap_webpack_plugin': 'str',
    'npm_package_devDependencies_storybook': 'str',
    'npm_package_devDependencies_style_loader': 'str',
    'npm_package_devDependencies_stylelint': 'str',
    'npm_package_devDependencies_stylelint_config_standard_scss': 'str',
    'npm_package_devDependencies_stylelint_scss': 'str',
    'npm_package_devDependencies_swc_loader': 'str',
    'npm_package_devDependencies_terser_webpack_plugin': 'str',
    'npm_package_devDependencies_ts_loader': 'str',
    'npm_package_devDependencies_ts_node': 'str',
    'npm_package_devDependencies_tsconfig_paths_webpack_plugin': 'str',
    'npm_package_devDependencies_typescript': 'str',
    'npm_package_devDependencies_typescript_eslint': 'str',
    'npm_package_devDependencies_webpack': 'str',
    'npm_package_devDependencies_webpack_cli': 'str',
    'npm_package_devDependencies_webpack_dev_server': 'str',
    'npm_package_devDependencies_workbox_webpack_plugin': 'str',
    'npm_package_lint_staged____ts_tsx__0': 'str',
    'npm_package_lint_staged____ts_tsx__1': 'str',
    'npm_package_lint_staged___scss_0': 'str',
    'npm_package_lint_staged___scss_1': 'str',
    'npm_package_name': 'str',
    'npm_package_packageManager': 'str',
    'npm_package_private': 'str',
    'npm_package_scripts_build': 'str',
    'npm_package_scripts_build_dev': 'str',
    'npm_package_scripts_build_prod': 'str',
    'npm_package_scripts_lint': 'str',
    'npm_package_scripts_postinstall': 'str',
    'npm_package_scripts_start': 'str',
    'npm_package_scripts_storybook': 'str',
    'npm_package_version': 'str',
    'offerhubBaseUrl': 'str',
    'opacity': 'str',
    'orderPlacementAttempts': 'str',
    'orderV1': 'str',
    'orderV2': 'str',
    'orderV3': 'str',
    'orderV4': 'str',
    'orderV5': 'str',
    'orderV6': 'str',
    'orderV7': 'str',
    'outline': 'str',
    'overflow': 'str',
    'overflowY': 'str',
    'padding': 'str',
    'paddingBottom': 'str',
    'paddingInline': 'str',
    'paymentMethods': 'str',
    'payment_active': {
    },
    'placement': 'str',
    'position': 'str',
    'providerName': 'str',
    'questions': 'str',
    'r': 'str',
    'recommendations': 'str',
    'response': {
    },
    'right': 'str',
    'size': 'str',
    'sm': 'str',
    'speed': 'str',
    'stroke': 'str',
    'strokeLinecap': 'str',
    'strokeMiterlimit': 'str',
    'strokeWidth': 'str',
    'suggest': 'str',
    'textDecoration': 'str',
    'thickness': 'str',
    'top': 'str',
    'transition': 'str',
    'type': 'str',
    'uploadImage': 'str',
    'user': {
    },
    'userSelect': 'str',
    'value': {
    },
    'variant': 'str',
    'verticalAlign': 'str',
    'viewBox': 'str',
    'w': 'str',
    'websocket': 'str',
    'whiteSpace': 'str',
    'width': 'str',
    'window': {
    },
    'xl': 'str',
    'xs': 'str',
    'а': 'str',
    'б': 'str',
    'в': 'str',
    'г': 'str',
    'д': 'str',
    'е': 'str',
    'ж': 'str',
    'з': 'str',
    'и': 'str',
    'й': 'str',
    'к': 'str',
    'л': 'str',
    'м': 'str',
    'н': 'str',
    'о': 'str',
    'п': 'str',
    'р': 'str',
    'с': 'str',
    'т': 'str',
    'у': 'str',
    'ф': 'str',
    'х': 'str',
    'ц': 'str',
    'ч': 'str',
    'ш': 'str',
    'щ': 'str',
    'ъ': 'str',
    'ы': 'str',
    'ь': 'str',
    'э': 'str',
    'ю': 'str',
    'я': 'str',
    'ё': 'str'
}

snapshots['test_get_news get_news'] = {
    'news': [
        {
            'annotation': 'str',
            'id': 'int',
            'preview_pic': 'NoneType',
            'preview_text': 'NoneType',
            'published_at': 'str',
            'title': 'str'
        }
    ]
}

snapshots['test_list categories_list'] = [
    {
        'additional_icons': [
        ],
        'categories': [
            {
                'additional_icons': [
                    {
                        'type': 'str',
                        'url': 'str'
                    }
                ],
                'advert': 'NoneType',
                'gradient_end': 'str',
                'gradient_start': 'str',
                'id': 'str',
                'image_link': 'str',
                'name': 'str',
                'title_color': 'str'
            }
        ],
        'id': 'str',
        'name': 'str'
    }
]

snapshots['test_list products_list'] = {
    'filters': [
        {
            'field_name': 'str',
            'filter_type': 'str',
            'list_values': 'NoneType',
            'name': 'str',
            'range_max_val': 'str',
            'range_min_val': 'str'
        }
    ],
    'name': 'str',
    'parent_id': 'str',
    'products': [
        {
            'badges': [
            ],
            'has_age_restriction': 'bool',
            'image_links': {
                'normal': [
                    'str'
                ],
                'small': [
                    'str'
                ]
            },
            'labels': [
                {
                    'bg_color': 'str',
                    'label': 'str',
                    'text_color': 'str'
                }
            ],
            'name': 'str',
            'plu': 'int',
            'prices': {
                'cpd_promo_price': 'NoneType',
                'discount': 'str',
                'regular': 'str'
            },
            'promo': 'NoneType',
            'property_clarification': 'str',
            'rating': {
                'rates_count': 'int',
                'rating_average': 'float'
            },
            'step': 'str',
            'stock_limit': 'str',
            'uom': 'str'
        }
    ]
}

snapshots['test_product_info product_info'] = {
    'assetPrefix': 'str',
    'buildId': 'str',
    'gip': 'bool',
    'isExperimentalCompile': 'bool',
    'isFallback': 'bool',
    'page': 'str',
    'props': {
        'pageProps': {
            '_sentryBaggage': 'str',
            '_sentryTraceData': 'str',
            'props': {
                'catalogStore': {
                    '_sections': [
                    ],
                    'banners': [
                    ],
                    'bannersFetchState': 'int',
                    'brands': [
                    ],
                    'inputs': {
                        'max': 'int',
                        'min': 'int'
                    },
                    'products': [
                    ],
                    'productsFetchState': 'int',
                    'productsList': [
                    ],
                    'productsListFetchState': 'int',
                    'productsPaginationFetchState': 'int',
                    'promotions': [
                    ],
                    'promotionsFetchState': 'int',
                    'recommendationFetch': 'int',
                    'sectionsFetchState': 'int',
                    'specificCategory': 'NoneType',
                    'specificCategoryFetchState': 'int',
                    'storeId': 'str'
                },
                'filtersPageStore': {
                    'page': 'int'
                },
                'isServerRendered': 'bool',
                'productStore': {
                    'product': {
                        'attributes': [
                            {
                                'name': 'str',
                                'uom': 'str',
                                'value': 'str'
                            }
                        ],
                        'badges': [
                        ],
                        'description': 'str',
                        'description_html': 'NoneType',
                        'description_md': 'str',
                        'has_age_restriction': 'bool',
                        'image_links': {
                            'normal': [
                                'str'
                            ],
                            'small': [
                                'str'
                            ]
                        },
                        'ingredients': 'str',
                        'ingredients_html': 'NoneType',
                        'is_available': 'bool',
                        'is_various_manufacturers': 'bool',
                        'labels': [
                            {
                                'bg_color': 'str',
                                'label': 'str',
                                'text_color': 'str'
                            }
                        ],
                        'name': 'str',
                        'nutrients': [
                            {
                                'text': 'str',
                                'value': 'str'
                            }
                        ],
                        'plu': 'int',
                        'prices': [
                            {
                                'placement_type': 'str',
                                'value': 'str'
                            }
                        ],
                        'promo': 'NoneType',
                        'property_clarification': 'str',
                        'rating': {
                            'rates_count': 'int',
                            'rating_average': 'float'
                        },
                        'step': 'str',
                        'stock_limit': 'str',
                        'uom': 'str'
                    },
                    'productFetchState': 'int'
                }
            }
        }
    },
    'query': {
        'pluWithSlug': 'str'
    },
    'scriptLoader': [
    ]
}

snapshots['test_rebuild_connection rebuild_connection'] = 'connection has been rebuilt'

snapshots['test_set_debug set_debug'] = False
