# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .files_update_metadata_response_data import FilesUpdateMetadataResponseDataParams
from .files_update_metadata_response_links import FilesUpdateMetadataResponseLinksParams
from .files_update_metadata_response_meta import FilesUpdateMetadataResponseMetaParams


class FilesUpdateMetadataResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[FilesUpdateMetadataResponseMetaParams]
    data: typing_extensions.NotRequired[FilesUpdateMetadataResponseDataParams]
    links: typing_extensions.NotRequired[FilesUpdateMetadataResponseLinksParams]
