from typing import Any, NamedTuple

def get_file_name_from_url(url: str) -> str: ...
def get_qs_dict(url: str) -> dict[str, list[str]]: ...
def get_qs_dict_flat(url: str) -> dict[str, str]: ...
def get_qs_value(url: str, key: str, default: Any = None) -> Any: ...
def split_url(url: str) -> NamedTuple: ...
def open_url(url_to_open: str) -> None: ...
def guess_user_agent(user_agents: dict, based_on_browser: str, default_ua: str) -> str: ...
