# This file provides type hints for the ebir_automation Python extension module built with PyO3.
# Place this file alongside the generated ebir_automation.pyd/.dll in your package directory.

# from ebir_automation import auto_open_ebir_window, eBIRFormsAutomation

class EBirformsAutomation:
    def __init__(self, hwnd: int) -> None: ...
    def type_tin(self, tin1: str, tin2: str, tin3: str, tin4: str) -> None: ...
    def select_form(self, form: str, fill_up: bool) -> bool: ...

def auto_open_ebir_window() -> int: ...
