# Generated by Django 5.0
# Custom migration to add stripe_data field to WebhookEndpoint model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0005_webhook_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='stripe_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ] 