#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@@$#?!!<<<!<!!?#$@@@@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@#!<<<!%#$$@@@@$$&#%?!!!!?&@@@@BBBBBBBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@@#!!%$@$@$@@$@@@@@@@@@@@@@@@$%!<%@@@BBBBBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@@?!%@@@@@@@$&$@$@@@@@@@@@@@@@@@@@@%>!$@@@BBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@?!&@@$$@@$$$&@$@$@@@@@@@@$$$@$$@@@@@@#>?@@@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@&<&@@$$$$@$$$$$$$$@$$$$$&&#&$$$$$$$$$@@@@<;&@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@#;%%%%&$$$$@@$$$$$@@$#?<><%#%?%#&&$$$$$@@@@#:$@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@:&#??%::=#@@@@$@@$$&;~_;:.-+:!?%%%&$$$$$@@@@%:@@@BBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@+@#?!?=+~<@@@@@@@$#?~::~~=;=~%%&#&&$$$$@@$@@@;%@@BBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@+@#???>+:&@@@@@@@&$$#>::++:<#&&&$$$$$@@$@@@@@%<@@@BBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@$;@&%##??#@@@@@@@@@@@@@$&&&###&$@@$$$$$@@@&$&@%<@@@BBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@;!&$@&&#&%$$$$@@$$@@@@$$$$&##%%%?$@@@@$$&&&&&$?;@@@BBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@&>%#?#$$$$$%?+><!%<!?%%%%%%#&$&?@@$:$@@&$&&#&%?%<+$@@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@#><$$$$%!<!?##%:~-;#$$@@@@@@@@@@?%@@$;#@$&$?%#<%>#&>+@@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBB@@@&##??&##!%#&@@@@#%#>:>?!%#&$$@@@@@@?%@@@$%<&%!!%%#!?#&?<:!@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBB@B@@$?;;%#&&%;&@@@$$&&$$&<&@@@$$@@@@@@@$<#@@@@@$>%#&&&??&$$#!+;&@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBB@@@#<!%?<??!><>@@@@@@@@&%$@$@@@@@@@@@@$!&@@@@@@@!%##?#$$@$&$!:>@@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBB@@&<%@@&!$@@&?&<#@@@@@@$$@@@@@@@@@@@@@$!&@@@@@@@@&<&#$@$$#&>&!:%$@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBB@@!<@@@#%@@@&<&@$<&@@@@@@@@@@@@@@@@@@@$<$@@@@@@@@@@%??&&&!?;>!#=?@@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBB@@@%?@@&!#@@@#<&@@$?>$@@@@@@@@@@@@@@@@@$<#@@@@@@@@@@@@?#??#?#?!&;?@@@@BBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBB@@$!@&!>#@@$?%@@@&!&#>@@@@@@@@@@@@@@$%<;?$&#$@@@@@@@@@$<$$$@@!&#;?@@BBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBB@@?<??!<%?>?@@@$%?$@&!?@@@@@@@@@@$$+~______~~%$@@@@@@@@#??$?&#&$:#@@BBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBB@@@%<$$&?!##;&&#!!&@@@$%:#$@@@$$@@$$?-,____,,,~>$$@@@@@@@@!##<<$$&+@@BBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBB@@%>@@@??$$$%>!?>@@@$%;!#>$@@@@@@@@$~~,,____,_-<$$@@@@@@@@$<##?@$<!@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBB@@#;@@$>%@@@#!&$?<&%?<;&$$#>$@@@@@@@$!+____-_--~?@@@@@@@@@@@&<@&#&+&@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBB@@@:$#<:!@@@#?$@@$#<?#>#@@@$<!@@@@@@@@@&<=-~+;>%$@@@@@@@@@@@@@!%&#><@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBB@@@%>??%;@@$!?@@@$!!&$&>%@&%!!;&@@@@@@@@@@$$$$@$#%%#$@@@@@@@@@@$>#!+$@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBB@@&<#@$&%;%?><@@@%;#@@@$&<<?%##<>@@@@@@@@@@@@@@@@@@$&%?#$@@@@@@@@&:+$@@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBBB@@@@<?$@@$??#&#;%#!><$@@@$??#$$$$<<;&@@@@@@@@@@@@@@@@@@@@$$#%%&@@@@$$#!@@@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBB@@@&;&@@@%%$@@$#?%%!;$@$%<>##$@$?!&#?!@@@@@@@@@@@@@@@@@@@@$@@@$&%%%$@$@?<@@@BBBBBBBBBBBBBBBBBB
#BBBBBBBBBB@@?=&#$%!$@@@#?&$&?!;!!?<>$@@$#<#@@$#;$@@@@@@@@@@@@@@@@@@@@@@@@@@@&%%%@$>&@@BBBBBBBBBBBBBBBBBB
#BBBBBBB@@@&;+&@::>&@@#<#$&!<#&$$&?>$@$?>%$@$%<>:#@@@@@@@@@@@@@@@@@@@@@@@@@@@$$$##?>$@@BBBBBBBBBBBBBBBBBB
#BBBBBB@@@%;>#&>;%$$?;<&%<;<%$@$?<<>??<;?&?!<>>?<<@@@@@@@@@@@@@@@@@@@$$$&%?!>!??%&@@@BBBBBBBBBBBBBBBBBBBB
#BBBBBB@@?;&;!;>&%<><;!<;!&@$&?<?&$&?><!!?#!>!##<;$@@@@@@@@@@$&%??!!!<<<!?!>#@@@@BBBBBBBBBBBBBBBBBBBBBBBB
#BBBB@@@&;%%&>><<<!?&#?>%@@#<!%!$$?>;#$$$?<?&&!;>;<$$$#%?!!<<>!???%%%###&<<@@@BBBBBBBBBBBBBBBBBBBBBBBBBBB
#BBBB@@@:#%=<>!<%$$%??>%%!;>&$$%?!<?@$%<!#&&!>>!!!<<<!??%%###&&&&$$$&#&>%$@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#BBBB@@#=;:%%?:??<;%$#>;<<;?<!!##>%?>:<&&?<>!!%#&&$&$$$$$$$@@@$@$$&?!?<&@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#BBB@@@&+>>>&%>:<&#%>>%&&?>>%&#?>:;;:;>>>!?%&$@@$@$$@@@@$$$$$$&&?>;<?&@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#BBB@@?:%!;!:>><%!;+>%%%!<><!<;:++;;;>><!?#$$&@@@$$@@@$$$$&&%??<<%@@@@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#@@@@<>%$&!!&&%<;!&&&&?><?!>;>?!#>+:+;:<<?>!%%#&%!#%%?%%!<>:;>!&&?>><&@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#@@@<?$??%%$%??%&$#%???><!%$@@@@@@$#@&!%!::<:+>;+;;;:>;><<>:<;~==+:::~@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#@@<%%:>&!:<&$#???&@@@B@@BBBBBBBB@@@@@@@@$#%:==+++:;;;;:::==+:::::;:;+?@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#@@>?%#?%#>!?%&@@@@@BBBBBBBBBBBBBBBBBBB@@$:---~++++:::::::+:::+:::<+::#@@@@@BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#@@@@@@@@@@@@@@BBBBBBBBBBBBBBBBBBBB@@@$!<>~--~~++=~~=++::::;::;;;>>><!<<;><&@@@@@@BBBBBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB@@@@@#::><>:;;>!???%??%%?%%%????%%%?????%%??><<!?$@@BBBBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBBBBB@@@#??!<;!!!<?><?%%%%??%???%%????!!!%?!!%%%%%??%%%%!:<&@@BBBBBBBBBBBBBBBBBBBB
#BBBBBBBBBBBBBBBBBBBBBBBB@@@&!;!%%!>!????<::;%?%%%%%%?%%%%%??%%%%?%%%%%%%%?%%%%%%%!<!$@BBBBBBBBBBBBBBBBBB
#
# Ain't fan!