from pathlib import Path
from typing import Any, Iterable

def batch_list(input_list: list[Any], batch_size: int) -> Iterable[list[Any]]: ...
def open_location(filepath: str | Path) -> bool: ...
