# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/listener/tls_inspector/v2/tls_inspector.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("TlsInspector",)

from dataclasses import dataclass

import betterproto2

from .......message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class TlsInspector(betterproto2.Message):
    """
    [#protodoc-title: TLS Inspector Filter]
    Allows detecting whether the transport appears to be TLS or plaintext.
    [#extension: envoy.filters.listener.tls_inspector]
    """

    pass


default_message_pool.register_message(
    "envoy.config.filter.listener.tls_inspector.v2", "TlsInspector", TlsInspector
)
