# coding: utf-8

"""
    ExKoin API Documentation

    API documentation for ExKoin Crypto exchange

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from exapi_client_python.api.pool_api import PoolApi


class TestPoolApi(unittest.TestCase):
    """PoolApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PoolApi()

    def tearDown(self) -> None:
        pass

    def test_private_pool_join_post(self) -> None:
        """Test case for private_pool_join_post

        """
        pass

    def test_private_pool_leave_post(self) -> None:
        """Test case for private_pool_leave_post

        """
        pass

    def test_private_pool_task_get(self) -> None:
        """Test case for private_pool_task_get

        """
        pass

    def test_private_pool_tasks_get(self) -> None:
        """Test case for private_pool_tasks_get

        """
        pass

    def test_public_pools_get(self) -> None:
        """Test case for public_pools_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
