# Generated by Django 4.2.20 on 2025-05-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0079_dataaccessrequest_lay_summary"),
        ("environment", "0016_remove_vminstance_gpu_attachable_gpuaccelerator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpuaccelerator",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("HBM2e", "HBM2e"),
                    ("GDDR5", "GDDR5"),
                    ("HBM3", "HBM3"),
                    ("GDDR6", "GDDR6"),
                    ("HBM2", "HBM2"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProjectResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workspace_project_id", models.CharField(max_length=50, unique=True)),
                ("bucket_name", models.CharField(max_length=50, unique=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_resource",
                        to="project.publishedproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Resource",
                "verbose_name_plural": "Project Resources",
            },
        ),
    ]
