# Generated by Django 4.2.20 on 2025-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0017_alter_gpuaccelerator_memory_type_projectresource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpuaccelerator",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("HBM2e", "HBM2e"),
                    ("GDDR6", "GDDR6"),
                    ("HBM2", "HBM2"),
                    ("GDDR5", "GDDR5"),
                    ("HBM3", "HBM3"),
                ],
                max_length=32,
            ),
        ),
    ]
