"""
Constants for streamlit_permalink.
"""

EMPTY_LIST_URL_VALUE = "_STREAMLIT_PERMALINK_EMPTY"
NONE_URL_VALUE = "_STREAMLIT_PERMALINK_NONE"
EMPTY_STRING_URL_VALUE = "_STREAMLIT_PERMALINK_EMPTY_STRING"
TRUE_URL_VALUE = "True"
FALSE_URL_VALUE = "False"

_BOOL_URL_VALUES = {TRUE_URL_VALUE, FALSE_URL_VALUE}
