
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-12T19:26:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "67a03760203da0b39e3efe53c2fbc1786b2627f2",
 "version": "0.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
