__title__ = "syzqemuctl"
__version__ = "0.2.6"
__description__ = "A command-line tool for managing QEMU virtual machines created through Syzkaller's create-image.sh."
__author__ = "Zhiyu Zhang"
__email__ = "zhiyuzhang999@gmail.com"
__license__ = "Apache-2.0"
__url__ = "https://github.com/QGrain/syzqemuctl"