from typing import Callable

__all__ = ['retry_http', 'retry_empty_dict', 'retry_json_error', 'retry_on_exception']

def retry_http(func: Callable, *, retries: int = 3, sleep: float = 0.4) -> Callable: ...
def retry_empty_dict(func: Callable, *, retries: int = 3) -> Callable: ...
def retry_json_error(func: Callable, *, retries: int = 3) -> Callable: ...
def retry_on_exception(func: Callable, *, retries: int = 3) -> Callable: ...
